/* IZURÉ Zwischenprüfung — Satz H22
   60 nachgebaute Aufgaben zur ZP Herbst 2022. Eigener Wortlaut, eigene Zahlen,
   Prüfinhalte und Aufgabenarten wie im Original. Hinweis: Die gelieferte Datei
   „Herbst 2023“ war inhaltlich identisch mit Herbst 2022 und ist deshalb hier enthalten. */
export default {
id:"H22", name:"Herbst 2022", note:"Nachbau · Originalreihenfolge (identisch mit gelieferter Datei „Herbst 2023“)",

items:[
/* ── TG 1 ─────────────────────────────────────────────────── */
{tg:1,g:"direct-response",src:"ZP H22/1",t:"mc",
 q:"Welches Beispiel ist dem Dialogmarketing zuzuordnen?",
 a:["Ein Fernsehsender blendet während einer Verkaufsshow eine Bestellhotline ein.","Großflächenplakate werben an der Autobahn für eine neue Marke.","Promoter verteilen Warenproben in der Fußgängerzone.","Ein Unternehmen sponsert die Trikots eines Fußballvereins.","Eine Zeitungsanzeige macht eine Marke ohne Kontaktmöglichkeit bekannt."],c:0,
 e:"Dialogmarketing will eine messbare Reaktion (Response) auslösen. Beim Direct Response bestellt der Zuschauer unmittelbar nach dem Spot über die eingeblendete Rufnummer. Plakat, Sponsoring und reine Imageanzeige zielen auf Bekanntheit (klassisches Marketing).",
 k:"Leistungen",s:"LF2 2.2.1"},
{tg:1,g:"outsourcing-vorteil",src:"ZP H22/2",t:"multi",
 q:"Welche zwei Gründe sprechen für einen Mobilfunkanbieter, seine Kundenhotline an einen externen Callcenter-Dienstleister zu vergeben?",
 a:["Kosten für eigenes Personal und eigene Infrastruktur sinken.","Schwankungen im Anrufvolumen lassen sich flexibel auffangen.","Die Agents identifizieren sich besonders stark mit den Produkten.","Die eigene Teamleitung kann jedes Gespräch unmittelbar kontrollieren.","Es entsteht kaum Schulungsbedarf, weil das Produktwissen vorhanden ist.","Abstimmungs- und Entscheidungswege werden kürzer."],cs:[0,1],
 e:"Vorteile des externen Callcenters: flexible Reaktion auf Volumenschwankungen (Overflow), durch Wettbewerb häufig kostengünstiger, Projekterfahrung, Zusatzservices. Nachteile: Schulungsbedarf, geringere Identifikation, langwierigere Abstimmung, eingeschränkte Qualitätskontrolle.",
 k:"Typologie",s:"LF2 2.1.1"},
{tg:1,g:"leistungsarten",src:"ZP H22/3",t:"match",
 q:"Ordnen Sie die Tätigkeiten der KommunikativAktiv KG zu.",
 pairs:[["technischer Support bei Installationsproblemen","Inbound-Leistung"],["Lagerhaltung, Versand und Retourenbearbeitung für einen Onlineshop","Zusatzleistung"],["Kundenadressen nach Postrückläufern telefonisch aktualisieren","Outbound-Leistung"],["Mailings drucken, kuvertieren und versenden","Zusatzleistung"],["ehemalige Kunden anrufen und zurückgewinnen","Outbound-Leistung"]],
 e:"Inbound: Bestellannahme, technische Hotline, Kundenservice, Informationshotline. Outbound: Telefonverkauf, Adress- und Datenqualifizierung, Kundenbindung, Kundenrückgewinnung, Inkasso, Marktforschung. Zusatzleistungen: Lettershop (Mailingversand), Fulfillment (Lager bis Retoure), E-Commerce.",
 k:"Leistungen",s:"LF2 2.2"},
{tg:1,g:"prozent-steigerung",src:"ZP H22/4",t:"calc",
 q:"Die Dialogfix GmbH bildete vor vier Jahren 8 Kaufleute für Dialogmarketing aus, heute sind es 14. Um wie viel Prozent ist die Zahl der Auszubildenden gestiegen?",
 ans:["75"],unit:"%",
 e:"Veränderung · 100 / Ausgangswert = (14 − 8) · 100 / 8 = 75 %. Häufiger Fehler: durch den neuen Wert teilen (6 / 14 = 42,9 %). Probe: 8 · 1,75 = 14.",
 k:"Branche & Historie",s:"LF2 1.1.2"},
{tg:1,g:"stellen-quali",src:"ZP H22/5",t:"match",
 q:"Ordnen Sie den Stellen im Callcenter das passende Anforderungs- bzw. Aufgabenprofil zu.",
 pairs:[["Callcenter-Manager","Hochschulstudium oder umfassende Weiterbildung und mehrjährige Callcenter-Erfahrung"],["Agent","Basisqualifikation, z. B. IHK-Zertifikat, Freude an der Kundenkommunikation"],["Trainer","pädagogisches Geschick, konzipiert und hält Schulungen"],["Teamleiter","Personal- und Urlaubsplanung, Coaching, meist zuvor selbst Agent"],["Controller","Kosten- und Leistungsrechnung, Steuerung und Kontrolle"]],
 e:"Buch LF2 2.3.1: Agent = Basisqualifikation ohne Führungsverantwortung; Teamleiter = führt 10 bis 20 Mitarbeiter, Personalplanung, Coaching; Manager = oberste Ebene, Studium bzw. Weiterbildung plus Erfahrung; Trainer = Schulungen; Controller = Kosten- und Leistungsrechnung.",
 k:"Mitarbeiter",s:"LF2 2.3.1"},
{tg:1,g:"service-phasen",src:"ZP H22/6",t:"mc",
 q:"Ein Onlinehändler für Bodenbeläge bietet folgende Leistungen an. Welche gehört zum Sales-Service?",
 a:["Berechnung der benötigten Menge während des Bestellgesprächs","kostenlose Musterproben vor der Kaufentscheidung","Online-Tool zur Farbauswahl auf der Website","telefonische Verlegehilfe nach der Lieferung","Verlängerung der Garantie nach dem Kauf"],c:0,
 e:"Sales-Service begleitet den Kauf selbst. Muster und Farbauswahl-Tool unterstützen vor dem Kauf (Pre-Sales); Verlegehilfe und Garantie wirken nach dem Kauf (After-Sales).",
 k:"Leistungen",s:"LF2 2.2.4"},

/* ── TG 2 ─────────────────────────────────────────────────── */
{tg:2,g:"englisch-telefon",src:"ZP H22/7",t:"mc",
 q:"Sie haben den Namen einer englischsprachigen Anruferin nicht verstanden. Welche Formulierung ist angemessen?",
 a:["I'm sorry, I didn't catch your name. Could you spell it, please?","Spell your name!","What is your problem?","I'll connect you.","Goodbye. Thanks for calling."],c:0,
 e:"Höflich um Wiederholung bzw. Buchstabieren bitten. „I'll connect you“ = Ich verbinde Sie; „Goodbye …“ beendet das Gespräch; Befehlsform und „What is your problem?“ wirken unhöflich.",
 k:"Gesprächsführung",s:"LF3 4.3"},
{tg:3,g:"bildschirm-fenster",src:"ZP H22/8",t:"mc",
 q:"Wie stellen Sie Ihren Bildschirm im Verhältnis zum Fenster auf, um Blendungen zu vermeiden?",
 a:["im rechten Winkel zum Fenster, sodass der Blick parallel zur Fensterfront verläuft","direkt vor das Fenster, damit der Blick ins Helle geht","mit dem Bildschirm zum Fenster, sodass Sie mit dem Rücken zum Fenster sitzen","direkt unter eine Deckenleuchte, unabhängig vom Fenster","möglichst nah an die Heizung unter dem Fenster"],c:0,
 e:"Buch LF1 4: Der Bildschirm sollte im rechten Winkel zum Fenster stehen, Sichtabstand mindestens 50 cm. Blick ins Fenster blendet, Fenster im Rücken spiegelt sich im Bildschirm.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:2,g:"stressoren",src:"ZP H22/9",t:"mc",
 q:"Eine Kollegin fühlt sich seit Wochen ausgelaugt. Welcher Umstand ist ein typischer Stressor, der zu Disstress führt?",
 a:["dauerhafte Überforderung, weil sie wegen Personalmangels zusätzliche Aufgaben übernimmt","ein Lob des Teamleiters für ein gelungenes Gespräch","eine geregelte Pausenplanung","ein ergonomisch eingerichteter Arbeitsplatz","klare Zuständigkeiten im Team"],c:0,
 e:"Stressoren sind äußere Reize, die Stress auslösen; Überforderung, Termindruck, Lärm oder schlechtes Betriebsklima führen häufig zu Disstress. Ein Lob kann positiven Eustress auslösen; Pausenplanung, Ergonomie und klare Zuständigkeiten beugen Stress vor.",
 k:"Stimme & Stress",s:"LF3 6.1"},
{tg:2,g:"offene-fragen",src:"ZP H22/10",t:"mc",
 q:"Wozu dienen offene Fragen im Kundengespräch vor allem?",
 a:["die Meinung und Befindlichkeit des Kunden kennenzulernen","den Kunden zu einer schnellen Entscheidung zu drängen","dem Kunden eine bestimmte Antwort in den Mund zu legen","Informationen am Ende des Gesprächs abzusichern","den Kunden zwischen zwei Terminen wählen zu lassen"],c:0,
 e:"Offene Fragen (W-Fragen) bringen ein Gespräch in Gang, bauen Beziehung auf und liefern viele Informationen zu Meinung, Befindlichkeit und Bedürfnissen. Absichern = geschlossene Frage, Antwort vorgeben = Suggestivfrage, zwei Termine = Alternativfrage.",
 k:"Gesprächsführung",s:"LF3 3.2.2"},
{tg:2,g:"rhetorische-argumentation",src:"ZP H22/11",t:"mc",
 q:"Welche Technik gehört NICHT zu den Formen der rhetorischen (verkürzten) Argumentation?",
 a:["die offene Frage nach den Bedürfnissen des Kunden","das Wenn-dann-Argument","die Verallgemeinerung","die Argumentation mit Autoritäten","die Entweder-oder-Technik"],c:0,
 e:"Das Buch nennt fünf Techniken der rhetorischen Argumentation: Wenn-dann, Verallgemeinerung, Argumentation mit Autoritäten, Entweder-oder und Argumentieren mit Statistiken. Eine offene Frage ist ein Instrument der Fragetechnik, kein Argument.",
 k:"Gesprächsführung",s:"LF3 3.2.1"},
{tg:2,g:"fuenfsatz-plan",src:"ZP H22/12",t:"mc",
 q:"Wie ist der Kettenbauplan der Fünfsatz-Technik aufgebaut?",
 a:["Einstiegssatz – drei aufeinander aufbauende Argumente – Zielsatz","These – Antithese – Synthese – Zielsatz","Aussage A – Begründung A – Aussage B – Begründung B – Zielsatz","Einstieg – Bezug auf bisherige Argumente – Argument 1 – Argument 2 – Zielsatz","These 1 – These 2 – Gemeinsamkeiten – Einigung – Zielsatz"],c:0,
 e:"Kettenbauplan: Die drei Argumente stehen logisch oder zeitlich in Beziehung zueinander. Die Distraktoren beschreiben den dialektischen Aufbau, den Vergleich, die Ausklammerung und den Kompromiss.",
 k:"Gesprächsführung",s:"LF3 3.2.1"},
{tg:2,g:"geschlossene-fragen",src:"ZP H22/13",t:"mc",
 q:"Welchen Zweck erfüllen geschlossene Fragen am Ende der Bedarfsermittlung?",
 a:["gezielt einzelne Sachverhalte abfragen und das Verstandene absichern","dem Kunden möglichst viel Antwortspielraum lassen","ein Gespräch überhaupt erst in Gang bringen","Zeit gewinnen, indem man auf eine Frage mit einer Frage antwortet","Interesse wecken, ohne eine Antwort zu erwarten"],c:0,
 e:"Geschlossene Fragen (Verb am Anfang, Antwort ja/nein bzw. kurze Sachangabe) sichern Informationen ab, steuern das Gespräch und führen zum Abschluss. Spielraum und Gesprächsbeginn = offene Frage, Frage auf Frage = Gegenfrage, keine Antwort erwartet = rhetorische Frage.",
 k:"Gesprächsführung",s:"LF3 3.2.2"},
{tg:2,g:"phasen-formulierung",src:"ZP H22/14",t:"match",
 q:"Ordnen Sie die Formulierungen der Gesprächsphase zu.",
 pairs:[["„Guten Tag, Dialogfix Kundenservice, mein Name ist Lea Brandt. Was kann ich für Sie tun?“","Begrüßung und Kontaktaufbau"],["„Nennen Sie mir bitte zum Abgleich Ihre Kundennummer und Ihr Geburtsdatum.“","Datenschutz (Legitimation)"],["„Wofür möchten Sie den Drucker hauptsächlich nutzen?“","Bedarfsermittlung"],["„Mit diesem Modell sparen Sie Tinte. Sind Sie mit dem Angebot einverstanden?“","Beratung und Lösung"],["„Kann ich sonst noch etwas für Sie tun, Herr Kaya?“","Gesprächsabschluss"]],
 e:"Beratungsgespräch in vier Schritten: Begrüßung/Kontaktaufbau (mit Meldeformel und Legitimation zum Datenschutz), Bedarfsermittlung, Beratung und Lösung (Nutzenargument, Ergebnis absichern), Gesprächsabschluss (Abschlussfrage mit Namen).",
 k:"Gesprächsführung",s:"LF5 1.1"},
{tg:2,g:"datenqualitaet",src:"ZP H22/15",t:"mc",
 x:"Outbound-Aktion der KommunikativAktiv KG: 9.200 Adressen geliefert · davon 8.100 nutzbar · 7.800 Zielpersonen erreicht · 1.593 Abschlüsse · 219 Stornos innerhalb der Widerrufsfrist.",
 q:"Über 1.100 der gelieferten Adressen sind nicht nutzbar. Welche Ursache liegt in der Qualität der Daten?",
 a:["Der Datensatz enthält viele Dubletten und veraltete Telefonnummern.","Die Agents erzielen eine zu hohe Erfolgsquote.","Der Servicelevel der Inbound-Hotline ist zu niedrig.","Die Stornoquote der Aktion ist zu hoch.","Die durchschnittliche Gesprächszeit ist zu kurz."],c:0,
 e:"Eine niedrige Ausschöpfung kann bedeuten, dass der gelieferte Datensatz von schlechter Qualität ist – z. B. viele Dubletten oder veraltete Daten. Erfolgs- und Stornoquote beziehen sich auf bereits erreichte Personen; Servicelevel und AHT sind Inbound-Kennzahlen.",
 k:"Kennzahlen",s:"LF5 5.2.1"},
{tg:2,g:"erfolgsquote",src:"ZP H22/16",t:"calc",
 x:"Outbound-Aktion der KommunikativAktiv KG: 9.200 Adressen geliefert · davon 8.100 nutzbar · 7.800 Zielpersonen erreicht (Nettokontakte) · 1.593 Abschlüsse · 219 Stornos.",
 q:"Wie hoch ist die Erfolgsquote der Aktion?",
 ans:["20,4"],unit:"%",hint:"Auf eine Nachkommastelle runden.",
 e:"Erfolgsquote = Erfolge · 100 / Nettokontakte = 1.593 · 100 / 7.800 = 20,4 %. Bezugsgröße sind die tatsächlich erreichten Zielpersonen, nicht die gelieferten oder nutzbaren Adressen.",
 k:"Kennzahlen",s:"LF5 5.2.2"},
{tg:2,g:"storno-festbestellung",src:"ZP H22/17",t:"mc",
 x:"Outbound-Aktion: 7.800 Nettokontakte · 1.593 Abschlüsse · 219 Stornos innerhalb der Widerrufsfrist.",
 q:"Welche Aussage zu den Stornos dieser Aktion trifft zu?",
 a:["Ohne die Zahl der Stornos lässt sich die Festbestellquote nicht ermitteln.","Die Stornos werden für die Ausschöpfungsquote benötigt.","Stornos erhöhen die Zahl der Nettokontakte.","Die Stornoquote bezieht sich auf die gelieferten Adressen.","Stornos verbessern die Wirtschaftlichkeit der Aktion."],c:0,
 e:"Festbestellquote = (Erfolge − Stornos) · 100 / Nettokontakte – ohne Stornozahl keine „echten Erfolge“. Die Stornoquote bezieht sich auf die Gesamtaufträge; hohe Stornos verursachen Mehrkosten.",
 k:"Kennzahlen",s:"LF5 5.2.3"},
{tg:2,g:"festbestellquote",src:"ZP H22/18",t:"calc",
 x:"Outbound-Aktion: 7.800 Nettokontakte · 1.593 Abschlüsse · 219 Stornos innerhalb der Widerrufsfrist.",
 q:"Wie hoch ist die Festbestellquote?",
 ans:["17,6"],unit:"%",hint:"Auf eine Nachkommastelle runden.",
 e:"Festbestellungen = 1.593 − 219 = 1.374. Festbestellquote = 1.374 · 100 / 7.800 = 17,6 %. Nicht mit der Stornoquote verwechseln: 219 · 100 / 1.593 = 13,7 %.",
 k:"Kennzahlen",s:"LF5 5.2.3"},
{tg:2,g:"zufriedenheit-befragung",src:"ZP H22/19",t:"mc",
 q:"Wann liefert eine Zufriedenheitsbefragung zur Servicehotline die aussagekräftigsten Ergebnisse?",
 a:["zeitnah nach dem abgeschlossenen Kontakt, z. B. per automatischer E-Mail oder Direktbefragung","einmal alle fünf Jahre per Postwurfsendung an alle Haushalte","nur bei Kunden, die sich bereits beschwert haben","ausschließlich bei den Mitarbeitern der Hotline","erst nach Ablauf der Gewährleistungsfrist"],c:0,
 e:"Das Buch nennt als Beispiel die automatische E-Mail nach einem Hotlinegespräch bzw. die Direktbefragung nach dem Kontakt – der Kunde erinnert sich dann genau. Eine Auswahl nur unzufriedener Kunden verzerrt das Ergebnis.",
 k:"Kundenbindung",s:"LF5 3.2"},
{tg:2,g:"reklamation-verhalten",src:"ZP H22/20",t:"multi",
 q:"Ein Kunde reklamiert, dass in seinem Paket das Ladekabel fehlt. Welche drei Verhaltensweisen sind richtig?",
 a:["Verständnis für den Ärger zeigen","auf die Schilderung eingehen und gezielt nachfragen","eine verbindliche Lösung anbieten, z. B. kostenfreien Nachversand","ausführlich erklären, wie der Fehler im Lager entstanden ist","anzweifeln, ob das Kabel wirklich fehlt","auf die AGB verweisen und das Gespräch beenden","sofort eine Lösung nennen, bevor der Kunde ausgeredet hat"],cs:[0,1,2],
 e:"Beschwerdemanagement: emotionale Ebene klären, sachlichen Hintergrund ermitteln, verbindliche Lösung finden. „Interne Fehler erklären“, „Reklamation anzweifeln“ und „Lösung zu schnell anbieten“ gehören zu den zehn Fehlern im Beschwerdegespräch.",
 k:"Beschwerden",s:"LF5 4.1.2"},
{tg:2,g:"positiv-formulieren",src:"ZP H22/21",t:"mc",
 q:"Welche Formulierung ist positiv?",
 a:["„Bis morgen um 12 Uhr erhalten Sie von mir eine Lösung.“","„Da müssen Sie leider bis morgen warten.“","„Dafür bin ich nicht zuständig.“","„Das kann ja gar nicht sein.“","„Da lässt sich leider nichts machen.“"],c:0,
 e:"Positiv formulieren heißt: sagen, was geht, statt was nicht geht – ohne „müssen“, „nicht“, „kein“. Buchbeispiel: statt „Da müssen Sie zwei Tage warten“ besser „Binnen der nächsten 48 Stunden erhalten Sie eine Lösung.“",
 k:"Beschwerden",s:"LF5 4.1.3"},
{tg:2,g:"beschwerde-ursache",src:"ZP H22/22",t:"mc",
 q:"Welche Beschwerde ist mitarbeiterbezogen?",
 a:["„Die Dame am Telefon war gestern ausgesprochen unfreundlich.“","„Die Lieferung kam zwei Wochen zu spät.“","„Der Drucker druckt schon wieder Streifen.“","„Niemand fühlt sich für meinen Fall zuständig.“","„Das Preis-Leistungs-Verhältnis stimmt nicht.“"],c:0,
 e:"Beschwerdeursachen laut Buch: mitarbeiterbezogen (Unfreundlichkeit, fehlende Fachkompetenz), produkt-/dienstleistungsbezogen (Sachmangel, Preis-Leistung) und abwicklungsbezogen (Lieferzeit, unklare Zuständigkeiten, Bearbeitungszeiten).",
 k:"Beschwerden",s:"LF5 4.1.1"},
{tg:2,g:"beschwerde-schritte",src:"ZP H22/23",t:"order",
 q:"Bringen Sie die Handlungsschritte eines Beschwerdegesprächs in die Reihenfolge laut Fachbuch.",
 items:["in das Gespräch einsteigen","den sachlichen Hintergrund ermitteln","die emotionale Ebene klären","für das Anliegen eine Lösung finden","das Gespräch abschließen"],
 e:"Buch LF5 4.1.2: Einsteigen → sachlichen Hintergrund ermitteln → emotionale Ebene klären → Lösung finden → abschließen. Praxishinweis des Buches: Ist der Kunde schon zu Beginn sehr aufgebracht, wird zuerst die emotionale Ebene geklärt.",
 k:"Beschwerden",s:"LF5 4.1.2"},
{tg:2,g:"crm-def",src:"ZP H22/24",t:"mc",
 q:"Was versteht man unter Customer Relationship Management (CRM)?",
 a:["die Strategie, alle Unternehmensbereiche und -aktivitäten auf langfristige Kundenbeziehungen auszurichten","eine Software, die ausschließlich Kundenadressen speichert","das Anrufverteilsystem der Telefonanlage","das Mithören von Gesprächen zur Leistungskontrolle","ein Verfahren zur Datensicherung"],c:0,
 e:"CRM ist laut Buch eine Unternehmensstrategie: Alle Bereiche und Aktivitäten werden auf langfristige Kundenbeziehungen ausgerichtet, um den Erfolg und die Zufriedenheit der Kunden zu steigern. Software und Datenbanken sind nur Hilfsmittel.",
 k:"CRM",s:"LF5 3.1.1"},

/* ── TG 3 ─────────────────────────────────────────────────── */
{tg:3,g:"lerntypen",src:"ZP H22/25",t:"mc",
 q:"Welche Lernstrategie passt am besten zum motorischen Lerntyp?",
 a:["die neue Software direkt am System ausprobieren (Learning by Doing)","die Bedienungsanleitung laut vorlesen","sich ein farbiges Schaubild einprägen","mit Kollegen über die Funktionen diskutieren","einen Podcast über die Software hören"],c:0,
 e:"Motorisch = Nachmachen und selbst Ausprobieren. Vorlesen und Podcast = auditiv, Schaubild = visuell, Diskussion = kommunikativ.",
 k:"Information & Lernen",s:"LF1 6.8"},
{tg:3,g:"grossraum",src:"ZP H22/26",t:"mc",
 q:"Welche Aussage über Großraumbüros trifft zu?",
 a:["Kurze Kommunikationswege erleichtern die Abstimmung zwischen den Mitarbeitern.","Jeder Mitarbeiter hat Anspruch auf einen festen Wunscharbeitsplatz.","Dunkle Trennwände sind gesetzlich vorgeschrieben.","Ein Großraumbüro muss mindestens 40 Arbeitsplätze umfassen.","Die Kosten je Arbeitsplatz sind höher als im Einzelbüro."],c:0,
 e:"Vorteile laut Buch: vereinfachte Kommunikation, bis zu 20 % geringere Flächenkosten als Einzelbüros. Nachteile: Geräuschpegel, Ablenkung, Raumklima, fehlende Privatsphäre.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:4,g:"arbschg",src:"ZP H22/27",t:"mc",
 q:"Welche Aussage zum Arbeitsschutzgesetz ist FALSCH?",
 a:["Verantwortlich für Sicherheit und Gesundheit ist grundsätzlich der Arbeitnehmer.","Der Arbeitgeber muss Gefährdungen am Arbeitsplatz beurteilen und dokumentieren.","Die Beschäftigten sind bei Einstellung und vor Einführung neuer Arbeitsmittel zu unterweisen.","Grundgedanke des Gesetzes ist die Prävention.","Arbeitnehmer können sich regelmäßig arbeitsmedizinisch untersuchen lassen."],c:0,
 e:"Laut Buch ist der Arbeitgeber für Gesundheit und Sicherheit der Arbeitnehmer verantwortlich. Gefährdungsbeurteilung, Unterweisung, Prävention und arbeitsmedizinische Untersuchungen sind zentrale Regeln des ArbSchG.",
 k:"Schutzgesetze",s:"LF1 2.2.7"},
{tg:3,g:"beleuchtung",src:"ZP H22/28",t:"mc",
 q:"Welche Beleuchtungsstärke wird für Büro- und Bildschirmarbeitsplätze mindestens empfohlen?",
 a:["500 Lux","100 Lux","250 Lux","2.000 Lux","Die Beleuchtungsstärke ist nicht geregelt."],c:0,
 e:"Das Buch empfiehlt mindestens 500 Lux. Weitere Regeln: Tageslicht vorziehen, Blendung durch Jalousien vermeiden, gleichmäßig ausleuchten, bei Rechtshändern Licht von links.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:3,g:"eisenhower",src:"ZP H22/29",t:"mc",
 q:"Eine Aufgabe ist wichtig, aber nicht dringend. Wie behandeln Sie sie nach dem Eisenhower-Prinzip?",
 a:["fest terminieren und möglichst selbst erledigen (B-Aufgabe)","sofort mit höchster Priorität erledigen (A-Aufgabe)","delegieren (C-Aufgabe)","direkt in den Papierkorb (D-Aufgabe)","in die Pufferzeit der ALPEN-Methode schieben"],c:0,
 e:"Eisenhower: A = wichtig und dringend → sofort selbst; B = wichtig, nicht dringend → terminieren, selbst erledigen; C = dringend, nicht wichtig → delegieren; D = weder noch → Papierkorb.",
 k:"Information & Lernen",s:"LF1 6.1"},
{tg:3,g:"diagramm-art",src:"ZP H22/30",t:"mc",
 q:"Die Mitarbeiter- und Umsatzentwicklung der letzten zehn Jahre soll auf einer Folie dargestellt werden. Welche Darstellung eignet sich am besten?",
 a:["Kurvendiagramm","Kreisdiagramm","Organigramm","Flussdiagramm","Mindmap"],c:0,
 e:"Kurvendiagramm = Entwicklungen in einem Zeitraum (Mitarbeiter-, Umsatzentwicklung). Kreisdiagramm = Anteile an einem Ganzen; Organigramm = Aufbauorganisation; Flussdiagramm = Abläufe.",
 k:"Präsentation",s:"LF2 3.2"},
{tg:3,g:"multitasking",src:"ZP H22/31",t:"mc",
 q:"Was bedeutet der Begriff Multitasking ursprünglich bei Computersystemen?",
 a:["Mehrere Anwendungen laufen gleichzeitig ab.","Ein Programm wird auf mehreren Rechnern installiert.","Daten werden automatisch gesichert.","Mehrere Nutzer teilen sich ein Passwort.","Der Rechner wählt Telefonnummern automatisch an."],c:0,
 e:"Der Begriff stammt laut Buch aus der EDV und beschreibt die Fähigkeit von Computersystemen, verschiedene Anwendungen gleichzeitig ablaufen zu lassen. Übertragen auf den Menschen: mehrere Tätigkeiten zugleich ausführen.",
 k:"Datenmanagement",s:"LF5 2.4"},
{tg:3,g:"acd",src:"ZP H22/32",t:"mc",
 q:"Welche Aussage über die ACD (Automatic Call Distribution) trifft zu?",
 a:["Sie verteilt eingehende Anrufe nach dem Prinzip Longest Waiting und Longest Idle auf freie Agents.","Sie legt den Servicelevel des Unternehmens fest.","Sie regelt die Urlaubsplanung der Mitarbeiter.","Sie berechnet den Tagesgewinn des Callcenters.","Sie ist ein Sprachcomputer, der Anrufer per Tastenmenü vorsortiert."],c:0,
 e:"Die ACD steuert, verteilt und verwaltet das Anrufaufkommen und liefert Reports. Der Servicelevel wird vom Unternehmen vorgegeben, die ACD misst ihn nur. Das Tastenmenü gehört zur IVR (Verwechslungspaar ACD/IVR).",
 k:"Branchentechnik",s:"LF4 1.2.2"},
{tg:3,g:"ocr",src:"ZP H22/33",t:"mc",
 q:"Welche Funktion erfüllt ein OCR-Programm?",
 a:["Zeichen auf eingescannten Vorlagen werden erkannt und gedeutet.","Programme werden installiert und verwaltet.","Festplatten werden defragmentiert.","Unerwünschte E-Mails werden aussortiert.","Verdächtige Dateien werden in Quarantäne verschoben."],c:0,
 e:"OCR ermittelt Wahrscheinlichkeiten für die Deutung eingescannter Buchstaben und Ziffern und prüft sogar Wortzusammenhänge (Buchbeispiel „4ngebot“ → „Angebot“).",
 k:"Software",s:"LF4 2.2"},
{tg:3,g:"programm-aufgabe",src:"ZP H22/34",t:"match",
 q:"Mit welchem Programm erledigen Sie die Aufträge Ihres Teamleiters?",
 pairs:[["die fünf häufigsten Beschwerdegründe aus den Kundendatensätzen ermitteln","Datenbankprogramm"],["Ideen aus dem Teammeeting für eine Vorführung aufbereiten","Präsentationsprogramm"],["eine Statistik über die verschickten Anschreiben erstellen","Tabellenkalkulation"],["alte Papierprotokolle digitalisieren","OCR-Software"],["ein Musteranschreiben für Beschwerden entwerfen","Textverarbeitung"]],
 e:"Datenbank = Abfragen über Datensätze; Präsentation = visuelle Aufbereitung für Meetings; Tabellenkalkulation = Statistiken und Berechnungen; OCR = eingescannte Vorlagen in Text; Textverarbeitung = Briefe und Dokumente.",
 k:"Software",s:"LF4 2.2"},
{tg:3,g:"browser",src:"ZP H22/35",t:"mc",
 q:"Wozu dient ein Webbrowser?",
 a:["zum Abrufen und Anzeigen von Webseiten","zum Versenden von E-Mails über SMTP","zur Verwaltung der Hardware","zum Schutz vor Viren","zur Verteilung eingehender Anrufe"],c:0,
 e:"Der Browser ruft Webseiten ab und stellt sie dar; übertragen werden sie per HTTP bzw. verschlüsselt per HTTPS. Hardwareverwaltung = Betriebssystem, Virenschutz = Antivirenprogramm.",
 k:"Netze & Dienste",s:"LF4 1.1.6"},
{tg:3,g:"wms",src:"ZP H22/36",t:"mc",
 q:"Wofür nutzt ein Callcenter ein Workforce-Management-System (WMS)?",
 a:["für die Personaleinsatzplanung, also die Planung der Agent-Kapazitäten für die Hotline","für die Verteilung eingehender Anrufe nach Skills","für die Texterkennung eingescannter Briefe","für die Verschlüsselung von Webseiten","für den Abruf von E-Mails vom Server"],c:0,
 e:"Personaleinsatzplanungs-Software (PEP) und WMS planen die Agent-Kapazitäten, meist inklusive Urlaubsplanung, damit Fehlzeiten schon berücksichtigt sind.",
 k:"Software",s:"LF4 2.3"},
{tg:3,g:"bewegungsdaten",src:"ZP H22/37",t:"mc",
 q:"Welche Angabe ist ein Bewegungsdatum?",
 a:["die Bestellmenge","die Kundennummer","das Geburtsdatum des Kunden","die Artikelbezeichnung","die Anschrift des Kunden"],c:0,
 e:"Bewegungsdaten ändern sich häufig (Bestellmenge, Bestelldatum, Umsatz, Bestellstatus). Stammdaten ändern sich selten oder nie (Kundennummer, Geburtsdatum, Artikelbezeichnung, Anschrift).",
 k:"Datenbanken",s:"LF4 4.4"},
{tg:3,g:"db-ziel",src:"ZP H22/38",t:"mc",
 q:"Welches Ziel verfolgt die Speicherung von Daten in einer Datenbank?",
 a:["Daten effizient, widerspruchsfrei (konsistent) und dauerhaft speichern","Daten möglichst mehrfach ablegen, damit nichts verloren geht","Daten zusätzlich nur auf Papier sichern","Daten nach jeder Abfrage löschen","Datensätze ohne Schlüssel ablegen, um Speicher zu sparen"],c:0,
 e:"Ziel laut Buch: effiziente (sparsam, schneller Zugriff), konsistente (fehlerfrei, widerspruchsfrei) und dauerhafte Speicherung. Mehrfachablage erzeugt Redundanz und Widersprüche.",
 k:"Datenbanken",s:"LF4 4.1"},
{tg:3,g:"personenbezogen",src:"ZP H22/39",t:"mc",
 q:"Welche Angabe ist nach DSGVO und BDSG geschützt?",
 a:["die private E-Mail-Adresse einer Abteilungsleiterin","das Fremdkapital der GmbH","die Anzahl der Nettokontakte pro Stunde","die Bankverbindung der GmbH","der Firmenname der GmbH"],c:0,
 e:"Geschützt sind personenbezogene Daten natürlicher Personen. Juristische Personen wie die GmbH fallen nicht unter die Schutzbestimmungen; Kennzahlen ohne Personenbezug ebenfalls nicht.",
 k:"Datenschutz",s:"LF4 6.1"},
{tg:3,g:"eingabemaske",src:"ZP H22/40",t:"mc",
 q:"Wie lassen sich Eingabefehler in der Kundendatenbank technisch verringern?",
 a:["durch festgelegte Datenformate und Pflichtfelder in der Eingabemaske","durch längere Pausen der Agents","durch einen höheren Servicelevel","durch häufigeres Neustarten des PCs","durch den Verzicht auf Primärschlüssel"],c:0,
 e:"Pflichtfelder sichern die Vollständigkeit, feste Formate (z. B. fünfstellige PLZ, Datumsfeld) verhindern Fehleingaben. Das Buch nennt Pflichtfelder ausdrücklich beim Grundsatz der Vollständigkeit.",
 k:"Datenmanagement",s:"LF5 2.2"},
{tg:3,g:"usv",src:"ZP H22/41",t:"mc",
 q:"Womit schützt die Dialogfix GmbH ihre Server vor Datenverlust bei einem Stromausfall?",
 a:["mit einer unterbrechungsfreien Stromversorgung (USV) bzw. Notstromversorgung","mit einer Firewall","mit einem Spamfilter","mit einem Antivirenprogramm","mit einem SSL-Zertifikat"],c:0,
 e:"Die USV gehört zum physikalischen Schutz gegen Umwelteinflüsse. Firewall, Spamfilter, Antivirenprogramm und SSL schützen vor Angriffen, Schadsoftware bzw. beim Datentransfer – nicht vor Stromausfall.",
 k:"Datensicherheit",s:"LF4 5.2.6"},
{tg:3,g:"firewall",src:"ZP H22/42",t:"mc",
 q:"Ihre Firewall blockiert ohne Nachfrage alle Anwendungen, die nicht ausdrücklich freigegeben sind. Welche Sicherheitsstufe ist eingestellt?",
 a:["hoch","mittel","niedrig","deaktiviert","nur Paketfilterung ohne Regeln"],c:0,
 e:"Hoch = nur ausdrücklich freigegebene Programme, Unbekanntes wird ohne Nachfrage geblockt. Mittel = bei neuen Anwendungen wird der Benutzer gefragt. Niedrig = alles erlaubt, nur definierte Angriffe werden geblockt.",
 k:"Datensicherheit",s:"LF4 5.2.3"},
{tg:3,g:"virenwarnung",src:"ZP H22/43",t:"mc",
 q:"Nach dem Download eines Dokuments meldet das Antivirenprogramm einen Virenfund. Wie verhalten Sie sich richtig?",
 a:["nichts verändern und sofort die IT-Abteilung informieren","das Antivirenprogramm kurz deaktivieren und die Datei öffnen","die Datei an Kollegen weiterleiten, damit sie sie prüfen","den Stecker ziehen und an einem anderen Platz weiterarbeiten","die Warnung wegklicken und weiterarbeiten"],c:0,
 e:"Die IT-Richtlinien im Buch verbieten Veränderungen am Antivirensystem, insbesondere das Abschalten. Die Einstiegssituation LF4 Kap. 5 zeigt genau das Fehlverhalten: Warnung wegklicken, Schutz abschalten, Platz wechseln.",
 k:"Datensicherheit",s:"LF4 5.2.4"},

/* ── TG 4 ─────────────────────────────────────────────────── */
{tg:4,g:"stabsstelle",src:"ZP H22/44",t:"mc",
 q:"Was kennzeichnet eine Stabsstelle?",
 a:["Sie unterstützt mit speziellen Funktionen außerhalb des Tagesgeschäfts, meist ohne Weisungsbefugnis.","Sie ist die kleinste organisatorische Einheit und umfasst das Arbeitsgebiet einer Person.","Sie fasst sachlich zusammenhängende Stellen zusammen.","Sie darf anderen Stellen Weisungen erteilen.","Sie regelt die Weisungsbefugnisse im Unternehmen."],c:0,
 e:"Buchtabelle: Stelle = kleinste Einheit; Abteilung = Zusammenfassung von Stellen; Instanz = weisungsbefugte Stelle; Stabsstelle = unterstützende Stelle mit speziellen Funktionen (z. B. QM, Öffentlichkeitsarbeit); Leitungssystem = Regelung der Weisungsbefugnisse.",
 k:"Organisation",s:"LF1 1.2.1"},
{tg:4,g:"firma-zusatz",src:"ZP H22/45",t:"mc",
 q:"Dieter Krämer ist als Einzelkaufmann im Handelsregister eingetragen. Welche Firmierung ist NICHT zulässig?",
 a:["Dieter Krämer Einzelkaufmann","Dialog-Service Krämer e. K.","Dieter Krämer e. Kfm.","Krämer Telefonservice eingetragener Kaufmann","Krämer Callservice e. K."],c:0,
 e:"Die Firma muss einen Rechtsformzusatz enthalten (Buch LF1 1.3.1). Zulässig sind nach § 19 HGB „eingetragener Kaufmann“ bzw. allgemein verständliche Abkürzungen wie „e. K.“ oder „e. Kfm.“; „Einzelkaufmann“ ist kein zulässiger Zusatz (Gesetzesdetail ergänzt).",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"br-rechte",src:"ZP H22/46",t:"mc",
 q:"Bei welcher Maßnahme hat der Betriebsrat ein echtes Mitbestimmungsrecht, sodass seine Zustimmung erforderlich ist?",
 a:["Anordnung von Überstunden für das Inbound-Team","Investition in eine neue Telefonanlage","Erweiterung des Firmengebäudes","langfristige Personalplanung","Änderung der Unternehmensstrategie"],c:0,
 e:"Echte Mitbestimmung u. a. bei Arbeitszeit, Pausen, Überstunden, Unfallschutz, Arbeitskontrollen. Investitionen, Baumaßnahmen und langfristige Personalplanung lösen nur Informations- und Beratungsrechte aus. Versetzungen und Umgruppierungen ordnet das Buch den Mitwirkungsrechten (§ 99 BetrVG) zu.",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:4,g:"uvv-bg",src:"ZP H22/47",t:"mc",
 q:"Wo beschafft die Dialogfix GmbH die geltenden Unfallverhütungsvorschriften?",
 a:["bei der Berufsgenossenschaft","bei der Industrie- und Handelskammer","bei der Gewerkschaft ver.di","bei der Krankenkasse","bei der Bundesnetzagentur"],c:0,
 e:"Die Berufsgenossenschaften sind Träger der gesetzlichen Unfallversicherung und für Unfallverhütung zuständig; für Dialogmarketing ist es die Verwaltungs-Berufsgenossenschaft (VBG). Die Unfallverhütung regeln die „Grundsätze der Prävention“.",
 k:"Institutionen",s:"LF1 1.4"},
{tg:4,g:"leitungssystem",src:"ZP H22/48",t:"mc",
 x:"Organigramm: Unter der Geschäftsführung stehen die Zentralbereiche Personal und Finanzen. Darunter gliedert sich das Unternehmen in die Geschäftsbereiche „Inbound-Service“, „Outbound-Vertrieb“ und „Fulfillment“, jeweils mit eigener Ergebnisverantwortung.",
 q:"Welches Leitungssystem liegt vor?",
 a:["Spartenorganisation","Stablinienorganisation","Mehrlinienorganisation","Matrixorganisation","Projektorganisation"],c:0,
 e:"Spartenorganisation (Divisionalorganisation): Aufteilung in Geschäftsbereiche mit eigener Ergebnisverantwortung; die Leitung übernimmt strategische, die Sparten operative Aufgaben. Sie ist eine Form der Einlinienorganisation.",
 k:"Organisation",s:"LF1 1.2.2"},
{tg:4,g:"verguetung-faellig",src:"ZP H22/49",t:"mc",
 q:"Wann muss die Ausbildungsvergütung für den laufenden Monat spätestens gezahlt werden?",
 a:["spätestens am letzten Arbeitstag des Monats","am 15. des Folgemonats","zum Ende des Ausbildungsjahres","sobald das Berichtsheft vorgelegt wurde","am ersten Werktag des Monats im Voraus"],c:0,
 e:"Nach § 18 Abs. 2 BBiG ist die Vergütung für den laufenden Kalendermonat spätestens am letzten Arbeitstag des Monats zu zahlen (Gesetzesdetail, im Buch nicht ausgeführt; das Buch nennt die Pflicht zur angemessenen, jährlich steigenden Vergütung).",
 k:"BBiG",s:"LF1 2.1.3"},
{tg:4,g:"ausbildungsordnung",src:"ZP H22/50",t:"mc",
 q:"Wo sind die Prüfungsanforderungen für Zwischen- und Abschlussprüfung eines Ausbildungsberufs festgelegt?",
 a:["in der Ausbildungsordnung","im Rahmenlehrplan","im Ausbildungsvertrag","im betrieblichen Ausbildungsplan","im Berichtsheft"],c:0,
 e:"Die Ausbildungsordnung enthält Berufsbezeichnung, Dauer, Ausbildungsberufsbild, Ausbildungsrahmenplan und Prüfungsanforderungen. Der Rahmenlehrplan regelt nur den Berufsschulunterricht.",
 k:"Ausbildung",s:"LF1 2.1.1"},
{tg:4,g:"entgelt-uv",src:"ZP H22/51",t:"mc",
 q:"Eine Auszubildende wundert sich, dass auf ihrer Abrechnung kein Beitrag zur Unfallversicherung steht. Warum?",
 a:["Die gesetzliche Unfallversicherung wird allein vom Arbeitgeber finanziert.","Auszubildende sind nicht unfallversichert.","Der Beitrag ist in der Krankenversicherung enthalten.","Die Unfallversicherung ist freiwillig.","Der Beitrag wird erst nach der Probezeit fällig."],c:0,
 e:"Unfallversicherung: Träger Berufsgenossenschaften, alle Arbeitnehmer und Azubis versichert, Finanzierung nur durch den Arbeitgeber, Beitrag nach Gefahrenklasse des Betriebs.",
 k:"Sozialversicherung",s:"LF1 2.4.1"},
{tg:4,g:"tarifarten",src:"ZP H22/52",t:"mc",
 q:"Was wird typischerweise in einem Manteltarifvertrag geregelt?",
 a:["Urlaub, Arbeitszeit und Entgeltfortzahlung im Krankheitsfall","die konkrete Höhe der Gehälter in den einzelnen Tarifgruppen","die Zuordnung von Tätigkeiten zu Tarifgruppen","die Höhe der Ausbildungsvergütung","die Anschaffung einer neuen Telefonanlage"],c:0,
 e:"Manteltarifvertrag = Rahmenbedingungen (Urlaub, Arbeitszeit, Arbeitsschutz, Entgeltfortzahlung), langfristig. Entgeltrahmentarifvertrag = Zuordnung zu Tarifgruppen. Entgelttarifvertrag = konkrete Höhe von Löhnen, Gehältern, Ausbildungsvergütungen, Laufzeit meist 1–2 Jahre.",
 k:"Mitbestimmung",s:"LF1 2.3.4"},
{tg:4,g:"urlaub-jarbschg",src:"ZP H22/53",t:"mc",
 x:"Drei Auszubildende erhalten laut Vertrag je 25 Werktage Urlaub. Alter zu Beginn des Kalenderjahres: Nele 15 Jahre, Timo 17 Jahre, Jana 19 Jahre.",
 q:"Welche Aussage trifft zu?",
 a:["Timo erhält genau den gesetzlichen Mindesturlaub.","Nele erhält genau den gesetzlichen Mindesturlaub.","Jana erhält zu wenig Urlaub.","Alle drei erhalten zu wenig Urlaub.","Nele erhält mehr als den gesetzlichen Mindesturlaub."],c:0,
 e:"JArbSchG: unter 16 Jahren 30 Werktage, unter 17 Jahren 27, unter 18 Jahren 25 (Alter zu Beginn des Kalenderjahres). Nele (15) bekommt 5 Tage zu wenig, Timo (17) genau 25. Für Jana (19) gilt das BUrlG mit 24 Werktagen – sie liegt darüber.",
 k:"Schutzgesetze",s:"LF1 2.2.1"},
{tg:4,g:"ausbildungsrahmenplan",src:"ZP H22/54",t:"mc",
 q:"Welche Aussage über den Ausbildungsrahmenplan trifft zu?",
 a:["Er ist Teil der Ausbildungsordnung und gliedert die betrieblichen Kenntnisse und Fertigkeiten sachlich und zeitlich.","Er regelt den Unterricht in der Berufsschule.","Er wird von jedem Betrieb frei erstellt.","Er legt die Höhe der Ausbildungsvergütung fest.","Er ist Teil des Berufsbildungsgesetzes."],c:0,
 e:"Der Ausbildungsrahmenplan ist bundesweit Teil der Ausbildungsordnung. Auf seiner Basis erstellt der Betrieb den betrieblichen Ausbildungsplan. Den Berufsschulunterricht regelt der Rahmenlehrplan der KMK.",
 k:"Ausbildung",s:"LF1 2.1.1"},
{tg:4,g:"wegeunfall",src:"ZP H22/55",t:"mc",
 q:"Eine Auszubildende stürzt auf dem direkten Weg zur Arbeit mit dem Fahrrad. Wer übernimmt die Behandlungskosten?",
 a:["die gesetzliche Unfallversicherung (Berufsgenossenschaft)","die gesetzliche Krankenversicherung","die Auszubildende selbst","die Haftpflichtversicherung des Arbeitgebers","die gesetzliche Rentenversicherung"],c:0,
 e:"Die gesetzliche Unfallversicherung übernimmt die Kosten bei Unfällen am Arbeitsplatz und auf dem direkten Weg zur Arbeit (Wegeunfall) sowie bei Berufskrankheiten.",
 k:"Sozialversicherung",s:"LF1 2.4.1"},
{tg:3,g:"arbstaettv-bildschirm",src:"ZP H22/56",t:"mc",
 q:"Welche Anforderung an Bildschirmarbeitsplätze ist FALSCH?",
 a:["Die Tastatur muss fest mit dem Bildschirm verbunden sein.","Bildschirme müssen frei von störenden Reflexionen und Blendungen sein.","Arbeitsflächen müssen eine reflexionsarme Oberfläche haben.","Die Zeichen müssen scharf und flimmerfrei dargestellt werden.","Die Tastaturbeschriftung muss kontrastreich und gut lesbar sein."],c:0,
 e:"Nach ArbStättV muss die Tastatur vom Bildschirm getrennt und neigbar sein, damit eine ergonomische Haltung möglich ist (Detail der Verordnung). Reflexions- und Blendfreiheit von Bildschirm und Arbeitsfläche zitiert das Buch ausdrücklich.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:4,g:"sicherheit-buero",src:"ZP H22/57",t:"mc",
 q:"Welche Situation erfüllt die Sicherheitsanforderungen im Büro?",
 a:["Bodenanschlussdosen sind fußbodenbündig abgedeckt.","Der Bürostuhl steht auf vier Rollen.","Mehrere Schubladen des Rollcontainers lassen sich gleichzeitig herausziehen.","Kabel verlaufen lose quer über den Gang.","Der Lichtschalter befindet sich hinter einem Vorhang."],c:0,
 e:"Abgedeckte Bodendosen vermeiden Stolperstellen. Ein Bürostuhl braucht mindestens fünf Rollen (standsicher), gleichzeitig ausziehbare Schubladen lassen den Container kippen, lose Kabel sind Stolperfallen.",
 k:"Arbeitsschutz",s:"LF1 3.2"},
{tg:4,g:"energie-sparen",src:"ZP H22/58",t:"mc",
 q:"Welche Maßnahme senkt den Energieverbrauch im Büro?",
 a:["die Klimaanlage angemessen temperieren","Geräte über Nacht im Stand-by lassen","Bildschirmschoner einsetzen","Mehrfachsteckdosen ohne Schalter verwenden","bei laufender Klimaanlage die Fenster öffnen"],c:0,
 e:"Buchliste: Bildschirme ausschalten, Energiesparoptionen nutzen, Geräte komplett ausschalten statt Stand-by, Lampen ausschalten, Steckdosenleisten mit Kippschalter, Klimaanlage angemessen temperieren, sparsame Geräte kaufen.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"energy-star",src:"ZP H22/59",t:"mc",
 q:"Woran erkennen Sie besonders energiesparende Bürogeräte?",
 a:["am Energy-Star-Kennzeichen","am EMAS-Logo","am GS-Zeichen","am Grünen Punkt","am Fairtrade-Siegel"],c:0,
 e:"Das Energy-Star-Kennzeichen steht für energiesparende Bürogeräte. EMAS = geprüftes Umweltmanagement, GS = geprüfte Sicherheit (z. B. Bürostühle), Grüner Punkt = Verpackungen im Dualen System.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"krwg-gesetz",src:"ZP H22/60",t:"mc",
 q:"Welches Gesetz stellt den Recycling-Gedanken und die Abfallhierarchie in den Mittelpunkt?",
 a:["das Kreislaufwirtschaftsgesetz (KrWG)","das Bundes-Immissionsschutzgesetz","das Arbeitsschutzgesetz","das Bundesdatenschutzgesetz","die Gewerbeordnung"],c:0,
 e:"Das KrWG dient der Schonung natürlicher Ressourcen und der umweltverträglichen Beseitigung von Abfällen; schon der Name betont den Kreislauf der Wertstoffe. Das BImSchG schützt vor Luftverschmutzung und Lärm.",
 k:"Umweltschutz",s:"LF1 3.4"}
]};
