/* IZURÉ Zwischenprüfung — Satz H25
   60 nachgebaute Aufgaben zur ZP Herbst 2025. Eigener Wortlaut, eigene Zahlen;
   Prüfinhalte, Aufgabenarten und Reihenfolge wie im Original. Wo das Buch einen
   veralteten Rechtsstand hat (BetrVG-Wahlalter), gilt die aktuelle Rechtslage –
   im Erklärtext gekennzeichnet. */
export default {
id:"H25", name:"Herbst 2025", note:"Nachbau · Originalreihenfolge",

items:[
{tg:1,g:"offshoring",src:"ZP H25/1",t:"mc",
 q:"In einer Fachzeitschrift lesen Sie: „Ein Energieversorger betreibt seine Kundenhotline inzwischen über eine eigene Tochtergesellschaft in Rumänien, weil Personal- und Mietkosten dort deutlich niedriger sind.“ Wie wird diese Standortstrategie bezeichnet?",
 a:["Offshoring","Outsourcing","Reshoring","Insourcing","Crowdsourcing"],c:0,
 e:"Buchdefinition: Beim Offshoring verlagert ein Unternehmen Tätigkeiten ins Ausland; sie bleiben organisatorisch im Unternehmen (hier: eigene Tochter). Beim Outsourcing werden Tätigkeiten dagegen an ein anderes Unternehmen ausgelagert – die räumliche Entfernung spielt dabei keine Rolle. Die Rückverlagerung ins Inland (Reshoring) beschreibt das Buch als aktuellen Gegentrend.",
 k:"Branche & Historie",s:"LF2 1.1.3"},
{tg:1,g:"dienstleistung-merkmal",src:"ZP H25/2",t:"mc",
 q:"Ein Kunde fragt, warum er die Telefonberatung Ihres Unternehmens nicht vorab ausprobieren kann wie ein Gerät im Laden. Welches Merkmal von Dienstleistungen erklärt das?",
 a:["Dienstleistungen sind immaterielle Güter – sie sind nicht greifbar und lassen sich vor der Inanspruchnahme nicht begutachten.","Dienstleistungen können auf Vorrat erstellt und gelagert werden.","Dienstleistungen werden grundsätzlich ohne Mitwirkung des Kunden erbracht.","Dienstleistungen werden zeitlich versetzt zu ihrer Nutzung erstellt.","Dienstleistungen sind physische Güter mit festen, prüfbaren Eigenschaften."],c:0,
 e:"Dienstleistungen sind immateriell: nicht greifbar, nicht lagerfähig und vor dem Kauf nicht prüfbar. Erstellung und Inanspruchnahme fallen zeitlich zusammen, und der Kunde wirkt an der Erstellung mit. Deshalb muss Dialogmarketing Vertrauen in die Leistung besonders deutlich kommunizieren.",
 k:"Sektoren & DL",s:"LF2 1.2.2"},
{tg:1,g:"klassisch-vs-dm",src:"ZP H25/3",t:"mc",
 q:"Ein Getränkehersteller überlegt, ob er ein neues Produkt mit klassischer Werbung oder mit Dialogmarketing einführen soll. Welches Argument spricht für das klassische Marketing?",
 a:["Eine bundesweite Plakat- und TV-Kampagne erreicht in kurzer Zeit sehr viele Menschen und steigert den Bekanntheitsgrad.","Jeder Empfänger wird individuell und persönlich angesprochen.","Der Erfolg lässt sich über die Reaktionen der Empfänger rasch kontrollieren.","Streuverluste werden durch eine gezielte Zielgruppenauswahl gering gehalten.","Der Empfänger kann unmittelbar antworten und in einen Dialog treten."],c:0,
 e:"Buchtabelle „Klassisches Marketing vs. Dialogmarketing“: Klassisches Marketing spricht einseitig den Massenmarkt an, Ziel ist die Steigerung des Bekanntheitsgrades. Individuelle Ansprache, rasche Erfolgskontrolle, geringe Streuverluste und direkte Responsemöglichkeit sind Merkmale des Dialogmarketings.",
 k:"Marketing",s:"LF2 1.3.2"},
{tg:1,g:"dialog-vs-direkt",src:"ZP H25/4",t:"mc",
 q:"Welche Maßnahme ordnet das Buch dem Direktmarketing und nicht dem Dialogmarketing zu?",
 a:["Versand eines Frühjahrskatalogs an 200.000 Haushalte","Bestellannahme an der Hotline nach einem TV-Spot","individuelle Antwort-E-Mail auf eine Kundenanfrage","Beratung von Websitebesuchern im Chat","Outbound-Anruf zur Terminvereinbarung"],c:0,
 e:"Beide wollen eine messbare Reaktion (Response). Dialogmarketing setzt auf individuelle Kommunikation, vor allem per Telefon und neue Medien (Inbound/Outbound, Direct Response, Chat, individueller Schriftverkehr). Direktmarketing nutzt massenhafte, überwiegend schriftliche Kommunikation in gleicher Form: Massen-Mailings, Massen-E-Mails, Postwurfsendungen, Prospekte und Kataloge.",
 k:"Marketing",s:"LF2 1"},
{tg:1,g:"direct-response",src:"ZP H25/5",t:"mc",
 q:"Ein Teleshopping-Sender blendet während der Produktvorführung eine Bestellnummer ein; die Anrufe laufen in Ihrem Callcenter auf. Wie heißt diese Inbound-Leistung?",
 a:["Direct Response","Cross-Selling","Help Desk","Kundenrückgewinnung","Adressqualifizierung"],c:0,
 e:"Direct Response ist die Bestellung unmittelbar nach einem TV- oder Radiospot; wegen der Anrufspitzen wird oft ein Overflow-Callcenter eingesetzt. Cross-Selling ist der Verkauf zusätzlicher Produkte, ein Help Desk die unternehmensinterne technische Hotline; Kundenrückgewinnung und Adressqualifizierung sind Outbound-Leistungen.",
 k:"Leistungen",s:"LF2 2.2.1"},
{tg:1,g:"front-back",src:"ZP H25/6",t:"mc",
 q:"Welche Tätigkeit gehört typischerweise zum Backoffice?",
 a:["Rechnungen nach einem Kundenanruf erstellen und korrigieren","eingehende Anrufe an der Service-Hotline annehmen","Standardfragen im Kundenchat beantworten","einen Anrufer an die Fachabteilung weiterverbinden","Adressdaten telefonisch mit dem Kunden abgleichen"],c:0,
 e:"Frontoffice = direkter Kundenkontakt (Anrufe, Chat, Weitervermittlung, Datenabgleich im Gespräch), möglichst mit Lösung im Erstkontakt. Backoffice = weiterführende Sachbearbeitung ohne direkten Kundenkontakt, z. B. Rechnungserstellung.",
 k:"Typologie",s:"LF2 2.1.3"},
{tg:2,g:"din5008",src:"ZP H25/7",t:"mc",
 q:"Welche Aufgabe erfüllt die DIN 5008 für die Geschäftskorrespondenz?",
 a:["Sie liefert ein einheitliches Grundgerüst für übersichtliche, gut lesbare Schriftstücke.","Sie schreibt den Wortlaut von Geschäftsbriefen verbindlich vor.","Sie legt die Pflichtangaben auf Geschäftsbriefen fest.","Sie regelt die Rechtschreibung der deutschen Sprache.","Sie gilt ausschließlich für Briefe an Behörden."],c:0,
 e:"Die DIN 5008 enthält Schreib- und Gestaltungsregeln (Gliederung, Zahlen, Datum, Satzzeichen). Sie ist eine Norm, kein Gesetz, und gibt keinen Wortlaut vor. Die Pflichtangaben auf Geschäftsbriefen stammen aus dem HGB (§ 37a), die Rechtschreibung aus dem amtlichen Regelwerk.",
 k:"Schriftliche Kommunikation",s:"LF3 1.1"},
{tg:2,g:"din5008-datum",src:"ZP H25/8",t:"mc",
 q:"Welche Datumsschreibweise entspricht der DIN 5008?",
 a:["14. Oktober 2026","14.Oktober 2026","14/10/2026","Oktober 14, 2026","2026.10.14"],c:0,
 e:"Nach DIN 5008 sind zulässig: numerisch 14.10.2026 bzw. international 2026-10-14 sowie alphanumerisch 14. Oktober 2026 – mit Leerzeichen nach dem Tagespunkt. Schrägstriche, amerikanische Reihenfolge oder Punkte in der ISO-Schreibweise sind nicht normgerecht.",
 k:"Schriftliche Kommunikation",s:"LF3 1.1"},
{tg:2,g:"perspektive",src:"ZP H25/9",t:"mc",
 q:"Sie müssen einer Kundin mitteilen, dass eine vorzeitige Kündigung laut Vertrag nicht möglich ist. Sie möchten die Sache in den Vordergrund stellen, sodass niemandem die Schuld zugewiesen wird. Welche Formulierung wählen Sie?",
 a:["„Die Vertragsbedingungen sehen eine Kündigung vor Ablauf der Mindestlaufzeit leider nicht vor.“","„Ich finde, Sie hätten den Vertrag genauer lesen sollen.“","„Sie können leider nicht vorzeitig kündigen.“","„Wir haben entschieden, Ihre Kündigung abzulehnen.“","„Ich persönlich würde Ihnen gern helfen, darf aber nicht.“"],c:0,
 e:"Die Es-Formulierung stellt eine Sache in den Vordergrund, bezieht die Aussage auf keine Person, niemand hat die Schuld – geeignet für schlechte Nachrichten. Ich-Formulierung: persönliche Meinung, Entschuldigung, Zuständigkeit. Sie-Formulierung: für den Empfänger positive Aussagen, Appelle. Wir-Formulierung: das Unternehmen als geschlossene Einheit, z. B. bei Entscheidungen nach internen Regeln.",
 k:"Schriftliche Kommunikation",s:"LF3 1.2"},
{tg:2,g:"kollege-abwesend",src:"ZP H25/10",t:"mc",
 q:"Ein verärgerter Kunde verlangt eine Kollegin aus der Buchhaltung, die heute krank ist. Sie kennen sich in dem Sachgebiet nicht aus. Wie reagieren Sie am besten?",
 a:["Sie nehmen das Anliegen mit allen Details auf, sagen zu, sich zu kümmern, und rufen den Kunden zeitnah mit einer Antwort zurück.","Sie bitten den Kunden, es morgen noch einmal zu versuchen, wenn die Kollegin wieder da ist.","Sie legen den Kunden in die Warteschleife, bis sich zufällig eine zuständige Person findet.","Sie erklären dem Kunden, woran die Kollegin erkrankt ist.","Sie schalten den Lautsprecher ein, damit die Kollegen im Raum mithören und helfen können."],c:0,
 e:"Der Kunde darf nicht abgewimmelt werden – „keine Zuständigkeit“ nennt das Buch ausdrücklich als Fehler im Beschwerdegespräch. Sie übernehmen Verantwortung, klären den Sachverhalt intern und melden sich verbindlich zurück. Angaben zur Erkrankung einer Kollegin sind vertraulich; Mithören über Lautsprecher ohne Zustimmung verletzt den Datenschutz.",
 k:"Gesprächsführung",s:"LF5 1.1"},
{tg:2,g:"gespraechsfoerderer",src:"ZP H25/11",t:"multi",
 q:"Welche zwei Äußerungen wirken im Kundengespräch gesprächsfördernd?",
 a:["„Ich kann gut verstehen, dass Sie das ärgert, Frau Yilmaz.“","„Was ist Ihnen bei einem neuen Tarif besonders wichtig?“","„Sie müssen die Rechnung bis Freitag bezahlen!“","„Da machen Sie es sich aber sehr einfach.“","„Wenn Sie heute nicht zusagen, ist das Angebot weg.“","„Ach, das ist doch halb so wild.“"],cs:[0,1],
 e:"Gesprächsförderer signalisieren dem Kunden, dass er ernst genommen wird und eingeladen ist, sein Anliegen vorzutragen – z. B. Verständnis zeigen und offene Fragen stellen. Die übrigen Aussagen sind Gesprächsstörer laut Buch: Befehlen („müssen“), Bewerten, Drohen/Warnen, Herunterspielen.",
 k:"Gesprächsführung",s:"LF3 3.2.4"},
{tg:2,g:"offene-fragen",src:"ZP H25/12",t:"mc",
 q:"Ein Kunde sagt: „Mein Internet spinnt.“ In welcher Gesprächsphase befinden Sie sich jetzt, und welche Frageart setzen Sie vorwiegend ein?",
 a:["Bedarfsermittlung – offene Fragen, z. B. „Was genau passiert, wenn Sie eine Seite aufrufen?“","Bedarfsermittlung – Suggestivfragen, z. B. „Sie haben den Router doch sicher falsch angeschlossen?“","Gesprächsabschluss – geschlossene Fragen, z. B. „Ist sonst alles klar?“","Begrüßung – rhetorische Fragen, z. B. „Wer kennt das nicht?“","Lösungsphase – Alternativfragen, z. B. „Montag oder Dienstag?“"],c:0,
 e:"Fragetrichter: Zu Beginn der Bedarfsermittlung offene Fragen (W-Fragen), die viele Informationen liefern; zum Ende geschlossene Fragen zur Absicherung. Suggestivfragen sind manipulativ und gehören nicht in die Bedarfsermittlung.",
 k:"Gesprächsführung",s:"LF3 3.2.2"},
{tg:2,g:"legitimation",src:"ZP H25/13",t:"mc",
 q:"Ein Anrufer nennt seinen Namen und möchte Auskunft über seine letzte Rechnung. Welche Angaben eignen sich, um vorher seine Identität zu prüfen (Legitimation)?",
 a:["Kundennummer und Geburtsdatum","Wohnort und Lieblingsfarbe","die Rufnummer, von der er gerade anruft","der Name des Beraters, mit dem er zuletzt gesprochen hat","Postleitzahl und Straße"],c:0,
 e:"Vor der Auskunft über personenbezogene Daten ist die Identität zu prüfen – mit Daten, die nur der Kunde kennen kann. Das Buch nennt z. B. Kontonummer, Geburtsdatum, Datum der ersten Bestellung, Kundennummer, letzten Rechnungsbetrag oder eine selbst gewählte Sicherheitsfrage; Dialogfix fragt Kundennummer und Geburtsdatum ab. Adresse oder Rufnummer sind für Dritte leicht zugänglich.",
 k:"Gesprächsführung",s:"LF5 1.1.1"},
{tg:2,g:"responsequote",src:"ZP H25/14",t:"calc",
 x:"Die Dialog-GmbH hat für einen Kunden ein Mailing mit Antwortkarte verschickt.\nAuswertung nach vier Wochen:\nAntworten (Response): 1.042\nResponsequote: 8 %",
 q:"Wie viele Mailings wurden verschickt?",
 ans:["13.025","13025"],unit:"Mailings",hint:"Ganze Zahl.",
 e:"Responsequote = Antworten · 100 / versandte Mailings → versandte Mailings = 1.042 · 100 / 8 = 13.025. Probe: 8 % von 13.025 = 1.042. Gesucht ist der Grundwert – 8 % von 1.042 (= 83,36) wäre die falsche Bezugsgröße. Die Responsequote wird im Buch nicht eigens definiert; die Rechenlogik entspricht der Erfolgsquote (Erfolge · 100 / Nettokontakte).",
 k:"Kennzahlen",s:"LF5 5.2.2"},
{tg:2,g:"beschwerde-ursachen",src:"ZP H25/15",t:"multi",
 q:"Ein Onlinehändler erhält gehäuft Beschwerden. Welche zwei Ursachen sind abwicklungsbezogen?",
 a:["Die Bestellung kommt deutlich später als zugesagt an.","Die zugesagte Rückerstattung wird nicht wie versprochen ausgeführt.","Das gelieferte Gerät hat einen Sachmangel.","Der Agent war am Telefon unfreundlich.","Der Kunde empfindet das Preis-Leistungs-Verhältnis als schlecht.","Der Mitarbeiter wirkte fachlich unsicher."],cs:[0,1],
 e:"Das Buch ordnet Beschwerdeursachen drei Bereichen zu: produkt- bzw. dienstleistungsbezogen (Sachmangel, Preis-Leistungs-Verhältnis), mitarbeiter- bzw. interaktionsbezogen (Unfreundlichkeit, mangelnde Fachkompetenz) und abwicklungsbezogen (Lieferzeiten, Einhaltung von Zusagen, Bearbeitungszeiten).",
 k:"Beschwerden",s:"LF5 4.1.1"},
{tg:2,g:"manipulation",src:"ZP H25/16",t:"mc",
 q:"Ein Kunde sagt im Reklamationsgespräch: „Überall sonst bekommt man in so einem Fall sofort ein neues Gerät – das weiß doch jeder!“ Welche manipulative Strategie wendet er an?",
 a:["Verallgemeinern","Schmeicheln","Anteilnahme erwecken","Drohen","Übertreiben"],c:0,
 e:"Beim Verallgemeinern beruft sich der Kunde auf angeblich allgemeingültige Regeln („branchenüblich“), um einen Wissensvorsprung vorzutäuschen. Reaktion laut Buch: deutlich machen, dass es um sein konkretes Anliegen geht und Ihnen der einzelne Fall wichtig ist.",
 k:"Beschwerden",s:"LF5 4.1.4"},
{tg:2,g:"beschwerde-fehler",src:"ZP H25/17",t:"match",
 q:"Ordnen Sie die Äußerungen des Agents den Fehlern im Beschwerdegespräch zu.",
 pairs:[["„Ich weiß schon, worum es geht – ich schicke Ihnen einfach ein neues Gerät.“","Lösung zu schnell anbieten"],["„Hätten Sie die Bedienungsanleitung gelesen, wäre das nicht passiert.“","Schuld zuschieben"],["„Uns trifft keine Schuld, der Paketdienst hat gestreikt.“","Rechtfertigung"],["„Das kann eigentlich gar nicht sein, das Gerät ist geprüft.“","Reklamation anzweifeln"],["„Mein Kollege war im Urlaub, deshalb blieb Ihr Auftrag liegen.“","Interne Fehler erklären"]],
 e:"Das Buch nennt zehn Fehler im Beschwerdegespräch, u. a. Routine, innere Ablehnung, keine Zuständigkeit, den Kunden „erziehen“, Lösung zu schnell anbieten, Schuld zuschieben, Reklamation anzweifeln, Beschwerdegrund herunterspielen, interne Fehler erklären, Rechtfertigung. Rechtfertigung = äußere Umstände als Erklärung; interne Fehler erklären = Abläufe im eigenen Haus schildern.",
 k:"Beschwerden",s:"LF5 4.1.5"},
{tg:3,g:"pareto",src:"ZP H25/18",t:"mc",
 q:"Ihre Teamleiterin sagt: „Mit 20 % unserer Aufgaben erreichen wir 80 % des Ergebnisses – also erledigen wir diese zuerst.“ Auf welches Prinzip bezieht sie sich?",
 a:["Pareto-Prinzip","Eisenhower-Prinzip","ALPEN-Methode","Methode 635","Mindmapping"],c:0,
 e:"Pareto-Prinzip (80/20-Regel): 20 % der Aufgaben bringen 80 % des Arbeitserfolgs – entscheidend ist, das Wichtige zuerst zu tun. Eisenhower ordnet nach Wichtigkeit und Dringlichkeit, ALPEN ist eine Methode der Tagesplanung, 635 und Mindmapping sind Kreativ- bzw. Strukturierungstechniken.",
 k:"Information & Lernen",s:"LF1 6.1"},
{tg:3,g:"diagramm-art",src:"ZP H25/19",t:"mc",
 q:"Sie wollen in der Teamsitzung zeigen, welchen Anteil Telefon, E-Mail, Chat und Social Media am gesamten Kontaktaufkommen des letzten Monats hatten. Welche Darstellung wählen Sie?",
 a:["Kreisdiagramm","Liniendiagramm","Organigramm","Flussdiagramm","Streudiagramm"],c:0,
 e:"Ein Kreisdiagramm zeigt die Anteile eines Ganzen (100 %). Liniendiagramme stellen Entwicklungen über die Zeit dar, Säulen- und Balkendiagramme Größenvergleiche; Organigramm (Aufbauorganisation) und Flussdiagramm (Abläufe) sind keine Zahlendiagramme.",
 k:"Präsentation",s:"LF2 3.2"},
{tg:3,g:"gruppenarbeit-phasen",src:"ZP H25/20",t:"order",
 q:"Ihr Team soll in einer Gruppenarbeit die Wartezeiten an der Hotline verkürzen. Bringen Sie die Phasen der Gruppenarbeit in die richtige Reihenfolge.",
 items:["Ziel bestimmen: Wartezeit unter 30 Sekunden","Teilaspekte prüfen und Teilziele ableiten","Lösungsvorschläge sammeln, z. B. per Brainstorming","optimale Lösung anhand vereinbarter Kriterien auswählen","ausgewählte Lösung umsetzen","Abschlussbetrachtung: Ergebnis und Arbeitsweise auswerten"],
 e:"Die sechs Phasen laut Buch: 1. Bestimmung des Ziels, 2. Prüfung (Teilaspekte, Teilziele – noch keine Diskussion), 3. Sammeln von Lösungsvorschlägen, 4. Auswahl der optimalen Lösung, 5. Umsetzung, 6. Abschlussbetrachtung (Ergebnis und Arbeitsweise der Gruppe).",
 k:"Information & Lernen",s:"LF1 6.3"},
{tg:3,g:"lerntypen",src:"ZP H25/21",t:"match",
 q:"Welcher Lerntyp profitiert jeweils am meisten von der beschriebenen Lernmethode?",
 pairs:[["erstellt farbige Lernplakate und Schaubilder","visueller Lerntyp"],["nimmt den Stoff als Sprachmemo auf und hört ihn unterwegs an","auditiver Lerntyp"],["übt Kundengespräche im Rollenspiel und schreibt Karteikarten","motorischer Lerntyp"],["erklärt den Stoff der Lerngruppe und diskutiert offene Fragen","kommunikativer Lerntyp"]],
 e:"Visuell: Lernen über Sehen (Bilder, Grafiken, Mindmaps). Auditiv: Hören und lautes Sprechen. Motorisch (haptisch): Tun, Ausprobieren, Schreiben. Kommunikativ: Gespräch und Diskussion. Meist ist ein Mix der Kanäle am wirksamsten.",
 k:"Information & Lernen",s:"LF1 6.8"},
{tg:3,g:"ergonomie",src:"ZP H25/22",t:"multi",
 q:"Sie richten einen neuen Bildschirmarbeitsplatz ein. Welche zwei Maßnahmen dienen der Ergonomie?",
 a:["Bildschirmneigung und Sehabstand an den Nutzer anpassen","einen höhenverstellbaren Schreibtisch bereitstellen","auf jeden Schreibtisch eine Grünpflanze stellen","die Fenster den ganzen Tag gekippt lassen","die Raumtemperatur fest auf 26 °C einstellen","den Bildschirm direkt vor das Fenster stellen"],cs:[0,1],
 e:"Ergonomie heißt, den Arbeitsplatz an den Menschen anzupassen: Bildschirm (Neigung, Abstand, Höhe), Tisch und Stuhl müssen sich einstellen lassen. Pflanzen und Lüften betreffen das Raumklima; ein Bildschirm vor dem Fenster führt zu Blendung.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:3,g:"telefonkonferenz",src:"ZP H25/23",t:"mc",
 q:"Während einer Videokonferenz mit der Zentrale fällt Ihnen eine Frage ein, der Referent spricht aber gerade. Wie verhalten Sie sich?",
 a:["Sie notieren die Frage und stellen sie, sobald Fragen zugelassen sind.","Sie unterbrechen sofort, damit die Frage nicht verloren geht.","Sie besprechen die Frage leise mit Ihrer Sitznachbarin, während Ihr Mikrofon eingeschaltet ist.","Sie lassen Ihr Mikrofon dauerhaft offen, um jederzeit reagieren zu können.","Sie verlassen die Konferenz und klären die Frage später per E-Mail mit Kollegen."],c:0,
 e:"In Telefon- und Videokonferenzen gilt: nicht unterbrechen, Mikrofon stumm schalten, wenn man nicht spricht, Fragen notieren und zum vorgesehenen Zeitpunkt stellen. Nebengespräche bei offenem Mikrofon stören alle Teilnehmer.",
 k:"Kommunikationsmedien",s:"LF4 1.1.1"},
{tg:3,g:"skill-routing",src:"ZP H25/24",t:"mc",
 q:"Die Telefonanlage stellt einen Anruf zur Tarifberatung in türkischer Sprache direkt zu einer Agentin durch, die Türkisch spricht und für Tarife geschult ist. Welche Funktion ist hier aktiv?",
 a:["Skill Based Routing der ACD","Interactive Voice Response (IVR)","Predictive Dialing","Computer Telephony Integration (CTI)","Automatic Number Identification (ANI)"],c:0,
 e:"Das Skill Based Routing der ACD verteilt Anrufe an den Mitarbeiter, der aufgrund seiner Fähigkeiten (Skills) am besten helfen kann. Abgrenzung: IVR = Sprachdialogsystem, das den Anrufer per Tastenwahl/Sprache vorsortiert; CTI = Verknüpfung von Telefon und Computer (z. B. Kundenmaske öffnet sich); ANI = Übermittlung der Anrufernummer; Predictive Dialer = Wählsystem im Outbound.",
 k:"Branchentechnik",s:"LF4 1.2.2"},
{tg:3,g:"standardsoftware",src:"ZP H25/25",t:"mc",
 q:"Welche Aussage zur Standardsoftware ist zutreffend?",
 a:["Meist ist damit das Office-Paket mit Textverarbeitung, Tabellenkalkulation, Präsentations- und Datenbankprogramm gemeint.","Standardsoftware wird speziell für die Abläufe eines einzelnen Unternehmens programmiert.","Eine amtliche Richtlinie legt fest, welche Programme zur Standardsoftware gehören.","Standardsoftware ist nur als Komplettpaket erhältlich.","Das Workforce-Management-System gehört zur Standardsoftware."],c:0,
 e:"Laut Buch gibt es keine amtliche Richtlinie, was Standardsoftware ist; meist ist das Office-Paket gemeint, das es als Einzellösungen und als Komplettpaket gibt. Speziell programmierte Software ist Individualsoftware; Zeiterfassung, PEP/WMS und Kampagnenmanagement zählen zur Branchensoftware.",
 k:"Software",s:"LF4 2.2"},
{tg:3,g:"ocr",src:"ZP H25/26",t:"mc",
 q:"Eingehende Kundenbriefe werden eingescannt. Welche Software sorgt dafür, dass der Text danach durchsucht und bearbeitet werden kann?",
 a:["OCR-Software (Texterkennung)","Firewall","Spamfilter","ACD-Software","Tabellenkalkulation"],c:0,
 e:"OCR (Optical Character Recognition) wandelt eingescannte Bilder oder PDFs in editierbaren Text um und gleicht Erkennungsfehler mit einem Wörterbuch ab. Sie ist die Grundlage für die Digitalisierung von Dokumenten in einem Dokumenten-Management-System.",
 k:"Software",s:"LF4 2.2"},
{tg:3,g:"wms",src:"ZP H25/27",t:"mc",
 x:"Auszug aus dem Workforce-Management-System, Ansicht „Schichtinfo“ – Agentin L. Brandt, 14.10.:\nRahmenzeit 08:00–16:30 · Kommen 07:56 · Pause 12:00–12:30 · Gehen 16:34 · Status: anwesend",
 q:"Wofür wird diese Ansicht des WMS in erster Linie genutzt?",
 a:["Zeiterfassung der einzelnen Mitarbeiter","Auswahl neuer Bewerber","strategische Entscheidung über künftige Schichtmodelle","Überweisung der Schichtzulage durch die Bank","Pflege der Produktdatenbank"],c:0,
 e:"Kommen-, Gehen- und Pausenzeiten je Mitarbeiter sind Daten der Zeiterfassung, die im WMS mit Personaleinsatzplanung, Urlaubs- und Fehlzeitenplanung verknüpft ist. Strategische Entscheidungen über Schichtmodelle trifft die Leitung – nicht die Einzelansicht.",
 k:"Software",s:"LF4 2.3"},
{tg:1,g:"interne-ausschreibung",src:"ZP H25/28",t:"mc",
 q:"Die Dialog-GmbH schreibt die Stelle einer Teamleitung intern im Intranet aus. Wen spricht sie damit an?",
 a:["alle Mitarbeiter des Unternehmens","ausschließlich die Führungskräfte","nur die Mitglieder des Betriebsrats","externe Bewerber über Jobportale","nur die Auszubildenden"],c:0,
 e:"Neue Mitarbeiter werden über eine interne Stellenausschreibung (eigene Belegschaft) oder eine Stellenanzeige (externer Arbeitsmarkt) gesucht. Der Betriebsrat kann verlangen, dass Stellen vorab intern ausgeschrieben werden.",
 k:"Mitarbeiter",s:"LF2 2.3.1"},
{tg:1,g:"social-recruiting",src:"ZP H25/29",t:"mc",
 q:"Welcher Vorteil spricht für Social Media Recruiting?",
 a:["Kandidaten können anhand ihrer Profilangaben vorausgewählt und zielgenau angesprochen werden.","Es werden ausschließlich Personen erreicht, die aktiv eine Stelle suchen.","Es gehen dadurch grundsätzlich weniger Bewerbungen ein.","Es werden alle Erwerbstätigen in Deutschland erreicht.","Es wird nur das Know-how der eigenen Belegschaft genutzt."],c:0,
 e:"Social Media Recruiting erreicht auch passiv Suchende und erlaubt eine zielgruppengenaue Ansprache über Profil- und Interessendaten (unter Beachtung der DSGVO). Es erreicht nie „alle“, und das Nutzen eigener Mitarbeiter ist ein Merkmal der internen Personalbeschaffung. Hinweis: Social Media Recruiting behandelt das Buch nicht eigens – allgemeines Fachwissen.",
 k:"Mitarbeiter",s:"LF2 2.3.1"},
{tg:3,g:"produktdatenbank",src:"ZP H25/30",t:"mc",
 q:"Die Agents sollen sich schnell über technische Daten und Preise neuer Smartphones informieren können. Welche Datenbank nutzen sie dafür?",
 a:["Produktdatenbank","Lieferdatenbank","Kundenhistorie","Blacklist des Spamfilters","Personalakte"],c:0,
 e:"Mit der Kundendatenbank verbunden sind laut Buch u. a. Produkt-, Lösungs- und Lieferdatenbank. Die Produktdatenbank liefert Eigenschaften und Preise der Produkte; die Lieferdatenbank den Lieferstatus, die Kundenhistorie die bisherigen Kontakte eines Kunden.",
 k:"Datenmanagement",s:"LF5 2.2"},
{tg:3,g:"zeitstabilitaet",src:"ZP H25/31",t:"mc",
 q:"Eine Kundin wird neu angelegt. Welche Erfassung entspricht dem Grundsatz der Zeitstabilität?",
 a:["Geburtsdatum „12.03.1998“ statt Alter „28 Jahre“","Alter „28 Jahre“ statt Geburtsdatum","Status „Auszubildende“ ohne Angabe der Ausbildungsdauer","„derzeit arbeitslos“ ohne Erfassungsdatum","„Neukundin“ als dauerhafter Kundenstatus"],c:0,
 e:"Zeitstabilität: Daten so erfassen, dass sie für einen längeren Zeitraum gültig bleiben (Buchbeispiel: „Auszubildender“ nur mit Ausbildungsdauer). Das Geburtsdatum bleibt richtig, das Alter veraltet jedes Jahr. Weitere Grundsätze: Richtigkeit, Vollständigkeit, Redundanzvermeidung (Dubletten), Konsistenz.",
 k:"Datenmanagement",s:"LF5 2.2"},
{tg:3,g:"passwort",src:"ZP H25/32",t:"mc",
 q:"Welches Passwort erfüllt die Kriterien für ein sicheres Passwort am besten?",
 a:["Wq8#tZ2!mR","Dialog2026","Sommer!!","12345678","MariaMueller"],c:0,
 e:"Sichere Passwörter kombinieren Groß- und Kleinbuchstaben, Ziffern und Sonderzeichen, enthalten kein Wort aus dem Wörterbuch (Schutz gegen Dictionary-Angriffe) und sind mindestens 8 Zeichen lang (Schutz gegen Brute-Force).",
 k:"Datensicherheit",s:"LF4 5.2.1"},
{tg:3,g:"antivirus-funktion",src:"ZP H25/33",t:"mc",
 q:"Ihr Antivirenprogramm meldet: „Vollständige Prüfung abgeschlossen – 0 Bedrohungen gefunden.“ Welche Funktion wurde ausgeführt?",
 a:["Scan: Festplatten, Laufwerke und Dateien wurden auf Schadsoftware durchsucht.","Update: die Virensignaturen wurden aktualisiert.","Quarantäne: eine infizierte Datei wurde isoliert.","Wächter: ein Programm wurde beim Start in Echtzeit überwacht.","Firewall: der Netzwerkverkehr wurde gefiltert."],c:0,
 e:"Die vier Bestandteile eines Antivirenprogramms: Scan (Durchsuchen von Laufwerken und Dateien), Update (aktuelle Virensignaturen), Wächter (Echtzeitüberwachung) und Quarantäne (Isolieren verdächtiger Dateien). Die Firewall ist ein eigenes Schutzprogramm.",
 k:"Datensicherheit",s:"LF4 5.2.2"},
{tg:3,g:"blacklist",src:"ZP H25/34",t:"mc",
 q:"Ein Absender schickt seit Wochen Werbe-Spam an die Service-Adresse. Wie sorgen Sie dafür, dass seine Mails künftig nicht mehr zugestellt werden?",
 a:["Sie tragen die Absenderadresse in die Blacklist des Spamfilters ein.","Sie tragen die Absenderadresse in die Whitelist ein.","Sie antworten dem Absender und bitten um Austragung.","Sie öffnen den Anhang, um den Absender zu identifizieren.","Sie leiten alle Mails an die gesamte Belegschaft weiter."],c:0,
 e:"Blacklist = Liste von Adressen, von denen keine E-Mails angenommen werden; Whitelist = Adressen, die immer zugestellt werden. Auf Spam antworten bestätigt dem Absender eine aktive Adresse, Anhänge unbekannter Absender können Schadsoftware enthalten.",
 k:"Datensicherheit",s:"LF4 5.2.5"},
{tg:3,g:"prozent-zeit",src:"ZP H25/35",t:"calc",
 x:"To-do-Liste der Auszubildenden Lea, Arbeitstag 7,5 Stunden:\n· Berichtsheft führen: 36 Minuten\n· Kundenkorrespondenz, Teammeeting, Telefondienst: restliche Zeit",
 q:"Wie viel Prozent ihrer täglichen Arbeitszeit plant Lea für das Berichtsheft ein?",
 ans:["8"],unit:"%",
 e:"7,5 h = 450 Minuten → 36 · 100 / 450 = 8 %. Probe: 8 % von 450 Minuten = 36 Minuten. Fehlerquelle: Stunden und Minuten mischen – 36 / 7,5 = 4,8 ist keine Prozentangabe.",
 k:"Information & Lernen",s:"LF1 6.1"},
{tg:3,g:"datenschutz-umfang",src:"ZP H25/36",t:"mc",
 q:"Welche Daten schützt das Datenschutzrecht (DSGVO und BDSG)?",
 a:["alle personenbezogenen Daten, also alle Informationen über eine identifizierte oder identifizierbare natürliche Person","alle Daten eines Unternehmens einschließlich seiner Umsatzzahlen","nur Stammdaten wie Name und Anschrift","nur Daten juristischer Personen wie einer GmbH","nur Bewegungsdaten wie Bestellungen"],c:0,
 e:"Geschützt sind alle personenbezogenen Daten natürlicher Personen – Stamm- wie Bewegungsdaten. Daten juristischer Personen und reine Unternehmenskennzahlen fallen nicht darunter (sie können aber als Geschäftsgeheimnis geschützt sein).",
 k:"Datenschutz",s:"LF4 6.1"},
{tg:4,g:"gmbh-haftung",src:"ZP H25/37",t:"mc",
 q:"Welche Aussage zur Haftung einer GmbH trifft zu?",
 a:["Für die Verbindlichkeiten haftet den Gläubigern nur die GmbH mit ihrem Gesellschaftsvermögen.","Die Gesellschafter haften zusätzlich mit ihrem Privatvermögen.","Die Geschäftsführer haften immer persönlich für alle Schulden der GmbH.","Verluste werden sofort nach Köpfen auf die Gesellschafter verteilt.","Die Zahl der Gesellschafter ist gesetzlich auf fünf begrenzt."],c:0,
 e:"Laut Buch haftet den Gläubigern grundsätzlich nur die GmbH mit ihrem Gesellschaftsvermögen; es gilt eine strikte Trennung zum Privatvermögen der Gesellschafter. Die Zahl der Gesellschafter ist unbegrenzt; Gewinne werden nach Geschäftsanteilen verteilt.",
 k:"Recht",s:"LF1 1.3.3"},
{tg:4,g:"kg-haftung",src:"ZP H25/38",t:"mc",
 q:"Welche Aussage zur Kommanditgesellschaft ist gesetzlich zutreffend?",
 a:["Die Komplementäre haften unbeschränkt, also auch mit ihrem Privatvermögen.","Die Kommanditisten haften unbeschränkt mit ihrem gesamten Vermögen.","Die Kommanditisten führen die Geschäfte der KG.","Zur Gründung ist ein Mindestkapital von 25.000 € vorgeschrieben.","In eine KG dürfen keine neuen Gesellschafter aufgenommen werden."],c:0,
 e:"Komplementäre (Vollhafter) haften unbeschränkt, gesamtschuldnerisch und unmittelbar und führen die Geschäfte. Kommanditisten (Teilhafter) haften nur mit ihrer Einlage. Ein Mindestkapital gibt es bei der KG nicht; die Aufnahme neuer Gesellschafter nennt das Buch ausdrücklich als Vorteil.",
 k:"Recht",s:"LF1 1.3.2"},
{tg:4,g:"hr-eintrag",src:"ZP H25/39",t:"mc",
 q:"Die Mehler KG wird ins Handelsregister eingetragen. Welche Angabe gehört zur Eintragung?",
 a:["der Sitz der Gesellschaft","der Jahresumsatz","die Zahl der Mitarbeiter","die Anschriften aller Kunden","der Gewinn des letzten Geschäftsjahres"],c:0,
 e:"Eingetragen werden u. a. Firma und Sitz sowie – laut Buch – die Namen aller Gesellschafter und die Höhe der Einlagen der Kommanditisten. Das Handelsregister wird elektronisch beim Amtsgericht geführt; Personengesellschaften stehen in Abteilung A. Umsatz, Gewinn oder Mitarbeiterzahl werden nicht eingetragen.",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"ablauforganisation",src:"ZP H25/40",t:"mc",
 q:"Welche Aussage beschreibt die Ablauforganisation?",
 a:["Sie legt Arbeitsabläufe unter Berücksichtigung von Raum, Zeit, Mitarbeitern und Arbeitsmitteln fest und standardisiert sie.","Sie gliedert das Unternehmen in Stellen und Abteilungen.","Sie zeigt im Organigramm, wer wem gegenüber weisungsbefugt ist.","Sie legt fest, ob ein Ein- oder Mehrliniensystem gilt.","Sie ordnet Stabsstellen den Instanzen zu."],c:0,
 e:"Die Ablauforganisation gestaltet die Arbeitsabläufe (Workflow) und beherrscht sie durch Standardisierung und Routinen. Stellen, Abteilungen, Weisungsbefugnisse, Leitungssysteme und Stabsstellen gehören zur Aufbauorganisation. Beide stehen in engem Abhängigkeitsverhältnis.",
 k:"Organisation",s:"LF1 1.2.3"},
{tg:4,g:"ihk-aufgaben",src:"ZP H25/41",t:"mc",
 q:"Welche Beschreibung trifft auf die Industrie- und Handelskammer zu?",
 a:["Interessenvertretung der gewerblichen Wirtschaft mit Aufgaben in Beratung, Wirtschaftsförderung sowie Aus- und Weiterbildung","Träger der gesetzlichen Unfallversicherung","Behörde zur Überwachung der Arbeitsschutzgesetze","Interessenvertretung der Arbeitnehmer beim Abschluss von Tarifverträgen","freiwilliger Zusammenschluss von Callcenter-Unternehmen einer Branche"],c:0,
 e:"Buchtabelle „Externe Institutionen“: IHK = Interessenvertretung der gewerblichen Wirtschaft, zuständige Stelle nach BBiG, führt Zwischen- und Abschlussprüfung durch. Unfallversicherung = Berufsgenossenschaft, Überwachung der Schutzgesetze = Aufsichtsbehörden/Gewerbeaufsicht, Tarifverträge = Gewerkschaft, Branchenzusammenschluss = Interessenverband (z. B. CCV, DDV).",
 k:"Institutionen",s:"LF1 1.4"},
{tg:4,g:"kg-gewinn",src:"ZP H25/42",t:"calc",
 x:"Gesellschaftsvertrag der Hansen & Lenz KG (Auszug):\n· Komplementär Jan Hansen: Kapitaleinlage 150.000 €\n· Kommanditistin Mia Lenz: Kapitaleinlage 50.000 €\n· Gewinnverteilung: Jeder Gesellschafter erhält vorab 4 % seiner Einlage; der Rest wird im Verhältnis 3 : 2 (Hansen : Lenz) verteilt.\nJahresgewinn: 60.000 €",
 q:"Wie viel Prozent des Jahresgewinns erhält Jan Hansen?",
 ans:["62"],unit:"%",
 e:"Vorabverzinsung: Hansen 4 % von 150.000 = 6.000 €, Lenz 4 % von 50.000 = 2.000 € → 8.000 €. Restgewinn 60.000 − 8.000 = 52.000 €, 3 : 2 = 5 Teile à 10.400 € → Hansen 31.200 €, Lenz 20.800 €. Hansen gesamt 37.200 € → 37.200 · 100 / 60.000 = 62 %. Probe: Lenz 22.800 € + 37.200 € = 60.000 €. Hinweis: Das Buch nennt die 4-%-Verzinsung als gesetzliche Regel; seit dem MoPeG (1.1.2024) verteilt das Gesetz ohne Vertragsregel nach Beteiligungsverhältnis – deshalb ist die Regel hier als Vertragsklausel vorgegeben.",
 k:"Recht",s:"LF1 1.3.2"},
{tg:4,g:"gmbh-merkmal",src:"ZP H25/43",t:"mc",
 q:"Für welche Rechtsform schreibt das Gesetz ein Mindestkapital von grundsätzlich 25.000 € vor?",
 a:["GmbH","KG","OHG","Einzelunternehmen","eingetragener Kaufmann (e. K.)"],c:0,
 e:"Das Stammkapital der GmbH beträgt grundsätzlich mindestens 25.000 €; die Geschäftsanteile der Gesellschafter können unterschiedlich hoch sein. Personengesellschaften (KG, OHG) und Einzelunternehmen haben kein gesetzliches Mindestkapital.",
 k:"Recht",s:"LF1 1.3.3"},
{tg:4,g:"probezeit-kuendigung",src:"ZP H25/44",t:"mc",
 q:"Die Auszubildende Sara möchte nach sechs Wochen in eine andere Ausbildung wechseln; sie ist noch in der Probezeit. Wie kann sie kündigen?",
 a:["jederzeit ohne Einhaltung einer Frist und ohne Angabe von Gründen – aber schriftlich","nur mit einer Frist von vier Wochen und schriftlicher Begründung","mündlich gegenüber dem Ausbilder, ohne Frist","nur mit Zustimmung der IHK","gar nicht – in der Probezeit kann nur der Ausbildungsbetrieb kündigen"],c:0,
 e:"§ 22 BBiG: In der Probezeit können beide Seiten jederzeit ohne Kündigungsfrist und ohne Angabe von Gründen kündigen; die Kündigung muss schriftlich erfolgen. Die Vier-Wochen-Frist gilt erst nach der Probezeit, wenn der Auszubildende die Ausbildung aufgibt oder wechselt.",
 k:"BBiG",s:"LF1 2.1.4"},
{tg:4,g:"ausbildungsrahmenplan",src:"ZP H25/45",t:"mc",
 q:"Welcher Teil der Ausbildungsordnung gliedert die im Betrieb zu vermittelnden Fertigkeiten, Kenntnisse und Fähigkeiten sachlich und zeitlich?",
 a:["Ausbildungsrahmenplan","Rahmenlehrplan","Ausbildungsvertrag","Ausbildungsnachweis (Berichtsheft)","Berufsbild"],c:0,
 e:"Der Ausbildungsrahmenplan ist Teil der Ausbildungsordnung und die Grundlage des betrieblichen Ausbildungsplans. Der Rahmenlehrplan gilt für die Berufsschule; das Berufsbild nennt nur die Inhalte, ohne zeitliche Gliederung.",
 k:"Ausbildung",s:"LF1 2.1.1"},
{tg:4,g:"sgb9-pflichtplaetze",src:"ZP H25/46",t:"calc",
 x:"Die Dialog-GmbH beschäftigt im Jahresdurchschnitt:\n· 149 Arbeitnehmer auf Arbeitsplätzen im Sinne des SGB IX\n· 12 Auszubildende\nSGB IX (Auszug): Arbeitgeber mit mindestens 20 Arbeitsplätzen beschäftigen auf wenigstens 5 % der Arbeitsplätze schwerbehinderte Menschen. Stellen für Auszubildende zählen nicht mit. Bruchteile von 0,5 und mehr werden aufgerundet, kleinere abgerundet (bei weniger als 60 Arbeitsplätzen stets abgerundet).",
 q:"Wie viele Pflichtarbeitsplätze muss die Dialog-GmbH mit schwerbehinderten Menschen besetzen?",
 ans:["7"],unit:"Arbeitsplätze",
 e:"149 · 5 % = 7,45 → Bruchteil 0,45 < 0,5 → abrunden → 7 Pflichtarbeitsplätze. Typischer Fehler: Auszubildende mitzählen (161 · 5 % = 8,05 → 8). Buch: Pflicht ab 20 Beschäftigten, Quote 5 %; Auszubildenden- und Rundungsregel ergänzt aus dem SGB IX.",
 k:"Schutzgesetze",s:"LF1 2.2.6"},
{tg:4,g:"ausgleichsabgabe",src:"ZP H25/47",t:"mc",
 q:"Die Dialog-GmbH beschäftigt weniger schwerbehinderte Menschen, als die Pflichtquote verlangt. Welche Folge ergibt sich daraus?",
 a:["Sie muss für die unbesetzten Pflichtarbeitsplätze eine Ausgleichsabgabe zahlen.","Sie muss den Betrieb bis zur Erfüllung der Quote schließen.","Sie darf bis zur Erfüllung nur noch schwerbehinderte Bewerber einstellen.","Die Pflicht entfällt, wenn der Betriebsrat zustimmt.","Sie erhält vom Integrationsamt eine Unbedenklichkeitsbescheinigung."],c:0,
 e:"Wird die 5-%-Quote nicht erreicht, ist eine Ausgleichsabgabe zu zahlen, mit der anderweitig Arbeitsplätze für schwerbehinderte Menschen finanziert werden. Zweiter Schwerpunkt des Schwerbehindertenrechts: besonderer Kündigungsschutz – ohne Zustimmung des Integrationsamts ist eine Kündigung unwirksam.",
 k:"Schutzgesetze",s:"LF1 2.2.6"},
{tg:4,g:"br-groesse",src:"ZP H25/48",t:"calc",
 x:"Belegschaft der Nordlicht Service GmbH:\n· 2 Geschäftsführer\n· 5 leitende Angestellte\n· 186 Angestellte\n· 16 Auszubildende\nAlle Beschäftigten sind volljährig.\n§ 9 BetrVG (Auszug): 51 bis 100 Arbeitnehmer → 5 Mitglieder · 101 bis 200 → 7 · 201 bis 400 → 9",
 q:"Aus wie vielen Mitgliedern besteht der Betriebsrat?",
 ans:["9"],unit:"Mitglieder",
 e:"Arbeitnehmer im Sinne des BetrVG sind nach § 5 auch die zur Berufsausbildung Beschäftigten; Geschäftsführer und leitende Angestellte zählen nicht (§ 5 Abs. 2 und 3 BetrVG – ergänzt aus dem Gesetz). 186 + 16 = 202 → Stufe 201 bis 400 → 9 Mitglieder. Typischer Fehler: Auszubildende vergessen (186 → 7 Mitglieder).",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:4,g:"br-wahlrecht",src:"ZP H25/49",t:"mc",
 q:"Wer ist nach dem aktuellen Betriebsverfassungsgesetz bei der Betriebsratswahl wahlberechtigt (aktives Wahlrecht)?",
 a:["alle Arbeitnehmer ab 16 Jahren sowie Leiharbeitnehmer, die länger als drei Monate im Betrieb eingesetzt werden","alle Arbeitnehmer ab 18 Jahren; Leiharbeitnehmer grundsätzlich nicht","nur Arbeitnehmer, die mindestens sechs Monate dem Betrieb angehören","alle Arbeitnehmer ab 16 Jahren einschließlich der leitenden Angestellten","nur Mitglieder einer Gewerkschaft"],c:0,
 e:"§ 7 BetrVG in der Fassung seit 2021: wahlberechtigt sind alle Arbeitnehmer ab 16 Jahren; Leiharbeitnehmer, wenn sie länger als drei Monate im Betrieb eingesetzt werden. Das Buch nennt noch die alte Altersgrenze von 18 Jahren – maßgeblich ist die aktuelle Rechtslage, so auch in der Originalprüfung. Sechs Monate Betriebszugehörigkeit betreffen die Wählbarkeit (passives Wahlrecht).",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:4,g:"br-rechte",src:"ZP H25/50",t:"mc",
 q:"Für welche Maßnahme braucht die Geschäftsleitung zwingend die Zustimmung des Betriebsrats?",
 a:["Einführung eines Systems, mit dem Gespräche der Agents zur Leistungskontrolle mitgehört und ausgewertet werden","Planung des Personalbedarfs für das kommende Jahr","Verlagerung eines Standorts in eine andere Stadt","Investition in eine neue Telefonanlage","Erweiterung des Angebots um Chat-Support"],c:0,
 e:"Echte Mitbestimmung besteht laut Buch u. a. bei Beginn und Ende der täglichen Arbeitszeit, Pausen, Gesundheits- und Unfallschutz, Einführung von Arbeitskontrollen (Monitoring) und Überstunden. Personalplanung und wirtschaftliche Entscheidungen (Standort, Investitionen, Angebot) unterliegen nur Informations- und Beratungsrechten.",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:3,g:"buerostuhl",src:"ZP H25/51",t:"mc",
 q:"Welche Anforderung an einen Bürodrehstuhl im Callcenter ist richtig?",
 a:["Er muss sich individuell an den Nutzer anpassen lassen und standsicher sein – mit mindestens fünf Rollen.","Vier Rollen reichen, wenn die Rückenlehne hoch genug ist.","Armlehnen sind vorgeschrieben, eine Höhenverstellung nicht.","Ein Hocker ohne Lehne ist grundsätzlich vorzuziehen.","Er darf nicht verstellbar sein, damit keine Fehleinstellungen entstehen."],c:0,
 e:"Laut Buch muss ein guter Bürostuhl individuell anpassbar sein, wechselnde Sitzhaltungen erlauben (dynamisches Sitzen), den Körper gut abstützen und standsicher sein – mindestens fünf Rollen. Fehleinstellungen vermeidet eine Einweisung, nicht ein starrer Stuhl.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:4,g:"arbeitsschutz-beratung",src:"ZP H25/52",t:"multi",
 q:"Die Dialog-GmbH plant neue Arbeitsplätze und möchte sich zu Arbeitsschutz und Unfallverhütung beraten lassen. Welche zwei Stellen kommen dafür in Betracht?",
 a:["die Aufsichtsperson der zuständigen Berufsgenossenschaft","das Gewerbeaufsichtsamt bzw. Amt für Arbeitsschutz","die Verbraucherzentrale","das Amtsgericht (Handelsregister)","die Agentur für Arbeit","das Finanzamt"],cs:[0,1],
 e:"Die Berufsgenossenschaft (für kaufmännische Tätigkeiten die Verwaltungs-Berufsgenossenschaft) ist Träger der Unfallversicherung und für Unfallverhütung zuständig. Die staatlichen Aufsichtsbehörden (Gewerbeaufsicht, Amt für Arbeitsschutz) überwachen die Schutzgesetze und beraten Betriebe.",
 k:"Institutionen",s:"LF1 1.4"},
{tg:3,g:"grossraum",src:"ZP H25/53",t:"mc",
 q:"Die Geschäftsleitung plant ein Großraumbüro statt Einzelbüros. Welches Argument spricht aus Unternehmenssicht dafür?",
 a:["geringere Kosten je Arbeitsplatz durch bessere Flächenausnutzung","geringerer Geräuschpegel als in Einzelbüros","mehr Privatsphäre für die Mitarbeiter","individuell regelbares Raumklima für jeden Einzelnen","weniger Ablenkung durch Kollegen"],c:0,
 e:"Großraumbüros sparen Fläche und Kosten (der Buchtext nennt bis zu 20 % weniger Bürofläche) und vereinfachen die Kommunikation. Nachteile: Geräuschpegel, Ablenkung, schwieriges Raumklima, fehlende Privatsphäre.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:3,g:"beleuchtung",src:"ZP H25/54",t:"mc",
 q:"Welche Anforderung an die Beleuchtung eines Bildschirmarbeitsplatzes ist richtig?",
 a:["Der Arbeitsbereich ist gleichmäßig und blendfrei ausgeleuchtet.","Der Arbeitsplatz wird nur durch eine punktuelle Schreibtischlampe beleuchtet.","Leuchten werden so angeordnet, dass sie sich im Bildschirm spiegeln.","Der Raum wird möglichst dunkel gehalten, damit der Bildschirm besser lesbar ist.","Direktes Sonnenlicht auf dem Bildschirm verbessert die Lesbarkeit."],c:0,
 e:"Bildschirmarbeitsplätze brauchen eine ausreichende, gleichmäßige und blendfreie Beleuchtung ohne Spiegelungen auf dem Bildschirm; starke Hell-Dunkel-Kontraste ermüden die Augen.",
 k:"Arbeitsplatz",s:"LF1 4"},
{tg:4,g:"brandschutztuer",src:"ZP H25/55",t:"mc",
 q:"Welches Verhalten verstößt gegen den vorbeugenden Brandschutz?",
 a:["Eine Brandschutztür wird mit einem Holzkeil offen gehalten, damit die Kollegen schneller durchkommen.","Der Feuerlöscher hängt gut sichtbar und frei zugänglich im Flur.","Fluchtwege sind mit grün-weißen Rettungszeichen gekennzeichnet.","Die Brandschutzordnung hängt am Schwarzen Brett aus.","Die Kaffeemaschine wird nach Feierabend ausgeschaltet."],c:0,
 e:"Brandschutztüren sollen im Brandfall die Ausbreitung von Feuer und Rauch verhindern und müssen selbstständig schließen können. Ein Keil hebt diese Schutzwirkung auf – ein erheblicher Mangel.",
 k:"Arbeitsschutz",s:"LF1 3.3"},
{tg:4,g:"verpackg",src:"ZP H25/56",t:"mc",
 q:"Welche Regelung dient in erster Linie dem Umweltschutz?",
 a:["Verpackungsgesetz (VerpackG)","Bürgerliches Gesetzbuch (BGB)","Berufsbildungsgesetz (BBiG)","Jugendarbeitsschutzgesetz (JArbSchG)","Handelsgesetzbuch (HGB)"],c:0,
 e:"Das VerpackG enthält die Rücknahmepflicht für Verpackungen und verpflichtet Handel und Hersteller, Verpackungsabfälle vorrangig zu vermeiden, sonst wiederzuverwenden oder zu recyceln. Weitere Umweltgesetze laut Buch: KrWG, GewAbfV, UVPG, BImSchG.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"krwg-hierarchie",src:"ZP H25/57",t:"order",
 q:"Bringen Sie die Stufen der Zielhierarchie des Kreislaufwirtschaftsgesetzes in die richtige Reihenfolge – höchste Priorität zuerst.",
 items:["Abfallvermeidung","Wiederverwendung","Wiederverwertung (Recycling)","energetische Verwertung","Beseitigung"],
 e:"Buchbeispiele: 1. Vermeidung (Intranet statt Papier), 2. Wiederverwendung (Pfandflaschen), 3. Wiederverwertung/Recycling (Altpapier wird zu neuem Papier), 4. energetische Verwertung (Verbrennung zur Energiegewinnung), 5. Beseitigung (Deponie, z. B. defekte Tonerkartuschen als Sondermüll).",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"umweltbelastung",src:"ZP H25/58",t:"mc",
 q:"Welche Situation stellt eine betriebsbedingte Umweltbelastung dar?",
 a:["Aus einem defekten Laserdrucker gelangen gesundheitsschädliche Emissionen (Tonerstaub) in die Raumluft.","Ein Mitarbeiter fährt mit dem Fahrrad zur Arbeit.","Das Unternehmen bezieht Ökostrom.","Altpapier wird getrennt gesammelt.","Die Kantine bietet täglich ein vegetarisches Gericht an."],c:0,
 e:"Typische Umweltbelastungen im Dialogmarketing laut Buch: Papierverbrauch, Energieverbrauch und Abfall – insbesondere Problemabfall wie Tonerreste und Druckerpatronen. Emissionen defekter Geräte belasten Umwelt und Gesundheit; die übrigen Beispiele sind umweltschonende Maßnahmen.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"energie-sparen",src:"ZP H25/59",t:"mc",
 q:"Mit welcher Maßnahme senken Sie im Büroalltag ohne Aufwand den Stromverbrauch?",
 a:["Licht in Räumen und am Arbeitsplatz ausschalten, wenn es nicht benötigt wird","Monitore nach Feierabend im Stand-by-Modus lassen","Drucker grundsätzlich über Nacht eingeschaltet lassen","Ladegeräte dauerhaft in der Steckdose lassen","möglichst viele Dokumente farbig ausdrucken"],c:0,
 e:"Nicht benötigte Verbraucher ausschalten ist die einfachste Energiesparmaßnahme. Das Buch nennt ausdrücklich Geräte im Stand-by als Energieverbraucher.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"papierlos-ziel",src:"ZP H25/60",t:"mc",
 q:"Die Dialog-GmbH stellt interne Mitteilungen von Papierformularen und Hauspost auf E-Mail und Intranet um. Welches umweltorientierte Ziel verfolgt sie damit vorrangig?",
 a:["Abfallvermeidung","Zeitersparnis","Kostensenkung","Datensicherheit","höhere Mitarbeitermotivation"],c:0,
 e:"Buchbeispiel zur obersten Stufe des KrWG: Durch verstärkte Nutzung des Intranets vermindert die Dialogfix GmbH ihren Papierabfall um 30 %. Zeit- und Kostenersparnis sind ökonomische, keine ökologischen Ziele.",
 k:"Umweltschutz",s:"LF1 3.4"}
]};
