/* IZURÉ Zwischenprüfung — Izuré-Übungssatz
   Eigene Aufgaben im IHK-Format zu Buch-Hotspots, die in den fünf
   Originalprüfungen nicht oder nur am Rand vorkommen (Kommunikationsmodelle,
   Kennzahlen, Zahlungsverkehr, TK-Technik, Datensicherheit, Handelsrecht,
   Schutzgesetze). Grundlage: Westermann-Fachbuch LF1–LF5; wo die Rechtslage
   neuer ist als das Buch, steht das im Erklärtext. */
export default {
id:"X6", name:"Izuré-Übungssatz", note:"Eigene Aufgaben · Buch-Hotspots außerhalb der Originalprüfungen",

items:[
/* ── Themengebiet 1 ─────────────────────────────────────────────── */
{tg:1,g:"up-cross",src:"IZ Übung/1",t:"match",
 q:"Ordnen Sie die Verkaufssituationen der passenden Verkaufstechnik zu.",
 pairs:[["Die Kundin fragt nach Tarif S, der Agent empfiehlt den höherwertigen Tarif M.","Up-Selling"],["Zum Smartphone bietet der Agent eine passende Schutzhülle an.","Cross-Selling"],["Statt der Basisversicherung schließt der Kunde die Premiumversicherung ab.","Up-Selling"],["Zur Druckerbestellung verkauft der Agent zusätzlich Tonerkartuschen.","Cross-Selling"]],
 e:"Up-Selling = Verkauf eines höherwertigen Produkts statt des ursprünglich gewünschten. Cross-Selling = Verkauf zusätzlicher, ergänzender Produkte. Beide erfasst die Verkaufsquote (LF5). Klassisches Verwechslungspaar.",
 k:"Leistungen",s:"LF2 2.2.1"},
{tg:1,g:"contact-center",src:"IZ Übung/2",t:"mc",
 q:"Worin unterscheidet sich ein Contact Center von einem klassischen Callcenter?",
 a:["Das Contact Center betreut Kunden über mehrere Kanäle – Telefon, E-Mail, Chat, Social Media, Messenger.","Das Contact Center arbeitet ausschließlich im Outbound.","Das Contact Center ist immer ein externer Dienstleister.","Das Contact Center telefoniert nur mit Geschäftskunden (B2B).","Beide Begriffe bedeuten dasselbe."],c:0,
 e:"Callcenter = Kundenkontakt nur per Telefon. Contact Center = Multichannel (Telefon, E-Mail, Chat, Social Media, Messenger). Die Begriffe sind nicht synonym. Sind die Kanäle zusätzlich vernetzt, spricht man von Omnichannel.",
 k:"Typologie",s:"LF2 2.1.2"},
{tg:1,g:"typologie",src:"IZ Übung/3",t:"mc",
 q:"Die KommunikativAktiv KG arbeitet als externer Dienstleister für verschiedene Auftraggeber und telefoniert sowohl im Inbound als auch im Outbound. Wie ist sie in der Unternehmenstypologie einzuordnen?",
 a:["externer Dienstleister mit Mischform aus Inbound und Outbound","Inhouse-Callcenter im Inbound","Inhouse-Callcenter mit Mischform","externer Dienstleister nur im Outbound","Mischform aus intern und extern, nur im Inbound"],c:0,
 e:"Die Typologie kombiniert die Tätigkeit (Inbound, Outbound, Mischform) mit der organisatorischen Einbindung (intern, extern, Mischform) zu 9 Feldern. KommunikativAktiv ist extern und macht In- und Outbound (Buch: Typ 6); Dialogfix ist intern mit Mischform (Typ 3).",
 k:"Typologie",s:"LF2 2.1.1"},
{tg:1,g:"marketingmix",src:"IZ Übung/4",t:"match",
 q:"Ordnen Sie die Maßnahmen der Dialogfix GmbH dem passenden Instrument des Marketingmix zu.",
 pairs:[["Styleguide und Schulungen für die Kundenkommunikation","People (Personalpolitik)"],["betriebliches Vorschlagswesen zur Verbesserung interner Abläufe","Processes (Prozesspolitik)"],["Lounge-Bereich für Besucher","Physical facilities (Ausstattungspolitik)"],["Werbebanner in einer Computerzeitschrift","Promotion (Kommunikationspolitik)"],["Finanzierungsangebot ab 500 € Bestellwert","Price (Preispolitik)"]],
 e:"Die 4 klassischen P (Product, Price, Promotion, Place) werden für Dienstleistungen um People, Processes und Physical facilities zu den 7 P erweitert. Dialogmarketing gehört schwerpunktmäßig zur Kommunikationspolitik.",
 k:"Marketing",s:"LF2 1.3.1"},
{tg:1,g:"softskills-outbound",src:"IZ Übung/5",t:"multi",
 q:"Welche zwei Soft Skills sind laut Buch besonders für Mitarbeiter im Outbound wichtig?",
 a:["Frustrationstoleranz","Überzeugungskraft","Geduld","Einfühlungsvermögen","Zuhören können","Hilfsbereitschaft"],cs:[0,1],
 e:"Outbound verlangt aktive, durchsetzungsstarke Eigenschaften: Überzeugungskraft, Ehrgeiz, Zielstrebigkeit, Frustrationstoleranz, Selbstvertrauen, positives Denken. Inbound verlangt reaktive, empathische: Geduld, Einfühlungsvermögen, Zuhören können, Freundlichkeit, Hilfsbereitschaft.",
 k:"Mitarbeiter",s:"LF2 2.3.2"},
{tg:1,g:"ausbildungsberufe",src:"IZ Übung/6",t:"mc",
 q:"Welche Aussage zu den Ausbildungsberufen im Dialogmarketing trifft zu?",
 a:["Die Servicefachkraft wird in 2 Jahren ausgebildet; diese Ausbildung kann auf die 3-jährige Ausbildung zum Kaufmann/zur Kauffrau angerechnet werden.","Beide Berufe dauern 3 Jahre.","Die Servicefachkraft lernt 3 Jahre, Kaufleute 2 Jahre.","Kaufmännische Steuerung und Controlling gehören nur zur Ausbildung der Servicefachkraft.","Beide Berufe gibt es erst seit 2020."],c:0,
 e:"Seit 2006 gibt es zwei Berufe: Servicefachkraft für Dialogmarketing (2 Jahre) und Kaufmann/-frau für Dialogmarketing (3 Jahre). Kaufleute lernen zusätzlich Personal, kaufmännische Steuerung und Kontrolle, Qualitätssicherung sowie Vertrieb und Marketing.",
 k:"Mitarbeiter",s:"LF2 2.3.3"},
{tg:1,g:"querschnittsbranche",src:"IZ Übung/7",t:"mc",
 q:"Warum bezeichnet man das Dialogmarketing als Querschnittsbranche?",
 a:["Weil seine Leistungen in vielen verschiedenen Branchen erbracht werden und es in der amtlichen Statistik nicht als eigene Branche geführt wird.","Weil es ausschließlich zum primären Sektor gehört.","Weil es nur Cross-Selling betreibt.","Weil es rechtlich zur Industrie gezählt wird.","Weil es nur grenzüberschreitend tätig ist."],c:0,
 e:"Dialogmarketing wird z. B. im Handel, in Banken, Versicherungen, Telekommunikation und im öffentlichen Dienst eingesetzt. Das Statistische Bundesamt führt es nicht als eigene Branche – deshalb „Querschnittsbranche“. Es gehört zum tertiären Sektor.",
 k:"Sektoren & DL",s:"LF2 1.2.1"},
{tg:1,g:"inbound-outbound",src:"IZ Übung/8",t:"mc",
 q:"Wodurch unterscheidet sich Inbound von Outbound?",
 a:["Im Inbound geht die Initiative vom Kunden aus, im Outbound vom Unternehmen.","Im Inbound telefoniert man nur mit Neukunden, im Outbound nur mit Bestandskunden.","Inbound findet immer im Inhouse-Callcenter statt, Outbound immer beim Dienstleister.","Im Inbound werden nur E-Mails bearbeitet, im Outbound nur Telefonate.","Outbound macht den größten Teil aller Gespräche der Branche aus."],c:0,
 e:"Buchdefinition: Inbound = Bearbeitung eingehender Kontakte, der Kunde hat die Initiative, das Unternehmen reagiert. Outbound = aktives Zugehen des Unternehmens auf den Kunden. Outbound macht etwa ein Drittel aller Gespräche aus.",
 k:"Typologie",s:"LF2 2.1.1"},

/* ── Themengebiet 2 ─────────────────────────────────────────────── */
{tg:2,g:"kommunikationsmittel",src:"IZ Übung/9",t:"match",
 q:"Ordnen Sie die Beispiele dem passenden Kommunikationsmittel zu.",
 pairs:[["Tonfall und Sprechtempo","paraverbal"],["gewählte Worte im Gespräch","verbal"],["Mimik und Körperhaltung","nonverbal"],["Lautstärke und Pausen","paraverbal"],["Gestik beim Präsentieren","nonverbal"]],
 e:"Verbal = gesprochenes oder geschriebenes Wort. Paraverbal = hörbare Ausdrucksform (Tonfall, Lautstärke, Tempo, Stimmlage, Pausen). Nonverbal = sichtbare Körpersprache. Am Telefon entfällt das Sichtbare – deshalb müssen verbale und paraverbale Anteile übereinstimmen (Kongruenz). Verwechslungspaar paraverbal/nonverbal!",
 k:"Kommunikationsmodelle",s:"LF3 2.1"},
{tg:2,g:"watzlawick",src:"IZ Übung/10",t:"mc",
 q:"Wie lautet das erste Axiom nach Paul Watzlawick im Wortlaut?",
 a:["„Man kann nicht nicht kommunizieren.“","„Man kann nicht kommunizieren.“","„Man muss immer kommunizieren.“","„Jede Kommunikation hat einen Inhalts- und einen Beziehungsaspekt.“","„Kommunikation ist immer symmetrisch.“"],c:0,
 e:"Die doppelte Verneinung ist der Prüfungspunkt: Jedes Verhalten – auch Schweigen oder Wegsehen – ist eine Botschaft. Der Inhalts- und Beziehungsaspekt ist das 2. Axiom, symmetrisch/komplementär das 5.",
 k:"Watzlawick",s:"LF3 2.3"},
{tg:2,g:"transaktionsanalyse",src:"IZ Übung/11",t:"match",
 q:"Ordnen Sie die Äußerungen dem Ich-Zustand nach der Transaktionsanalyse (Eric Berne) zu.",
 pairs:[["„Das haben Sie falsch gemacht, das weiß doch jeder!“","kritisches Eltern-Ich"],["„Machen Sie sich keine Sorgen, ich kümmere mich darum.“","fürsorgliches Eltern-Ich"],["„Welche Fehlermeldung zeigt das Gerät genau an?“","Erwachsenen-Ich"],["„Ich will das jetzt sofort, sonst kündige ich!“","rebellisches Kind-Ich"],["„Wie toll, das probiere ich gleich aus!“","freies Kind-Ich"]],
 e:"Drei Ich-Zustände mit sechs Ausprägungen: Eltern-Ich (fürsorglich/nährend, kritisch), Erwachsenen-Ich (sachlich, lösungsorientiert), Kind-Ich (frei, angepasst, rebellisch). Verärgerte Kunden sprechen oft aus dem kritischen Eltern-Ich oder rebellischen Kind-Ich – Ziel ist der sanfte Wechsel ins Erwachsenen-Ich.",
 k:"Kommunikationsmodelle",s:"LF3 2.5"},
{tg:2,g:"transaktionsanalyse",src:"IZ Übung/12",t:"mc",
 q:"Ein Agent fragt sachlich: „Welche Version der Software nutzen Sie?“ Der Kunde antwortet: „Belehren Sie mich nicht, ich bin doch kein Anfänger!“ Welche Transaktion liegt vor?",
 a:["gekreuzte Transaktion","parallele Transaktion","verdeckte Transaktion","komplementäre Transaktion","symmetrische Transaktion"],c:0,
 e:"Der Agent spricht aus dem Erwachsenen- das Erwachsenen-Ich an; die Antwort kommt aus einem anderen Zustand (Kind-Ich gegen vermutetes Eltern-Ich) – das ist eine gekreuzte Transaktion, sie führt oft zu Störungen. Parallel = Antwort aus dem angesprochenen Zustand; verdeckt = zwei Ebenen gleichzeitig. Symmetrisch/komplementär sind Begriffe aus Watzlawicks 5. Axiom.",
 k:"Kommunikationsmodelle",s:"LF3 2.5"},
{tg:2,g:"johari",src:"IZ Übung/13",t:"mc",
 q:"Nach einem Coaching sagt die Teamleiterin zu Ihnen: „Dir ist wohl nicht bewusst, dass du im Gespräch oft seufzt.“ Welcher Bereich des Johari-Fensters wird durch dieses Feedback verkleinert?",
 a:["der blinde Fleck","die öffentliche Person (Arena)","die Privatperson","das Unbekannte","der Beziehungsaspekt"],c:0,
 e:"Blinder Fleck = anderen bekannt, mir selbst unbekannt – er wird durch Feedback kleiner. Offenheit (Selbstoffenbarung) verkleinert dagegen den Bereich Privatperson. Beides vergrößert die Arena (öffentliche Person).",
 k:"Kommunikationsmodelle",s:"LF3 2.6"},
{tg:2,g:"maslow",src:"IZ Übung/14",t:"order",
 q:"Bringen Sie die Stufen der Bedürfnispyramide nach Maslow in die richtige Reihenfolge – von unten nach oben.",
 items:["physiologische Grundbedürfnisse","Sicherheitsbedürfnisse","soziale Bedürfnisse","Wertschätzung und Anerkennung","Selbstverwirklichung"],
 e:"Höhere Stufen werden laut Maslow erst relevant, wenn die darunterliegenden erfüllt sind: Essen/Schlaf → Schutz/Arbeitsplatz → Zugehörigkeit → Lob/Status → persönliche Entwicklung.",
 k:"Kommunikationsmodelle",s:"LF3 2.8"},
{tg:2,g:"aktives-zuhoeren",src:"IZ Übung/15",t:"mc",
 q:"Welche Reaktion ist ein Beispiel für aktives Zuhören?",
 a:["„Sie ärgern sich also, weil die Lieferung schon zum zweiten Mal zu spät kommt.“","„Das passiert bei uns eigentlich nie.“","„Mhm … Moment, ich schaue kurz in meine Mails.“","„Da hätten Sie eben früher bestellen müssen.“","„Wie war noch mal Ihr Name?“"],c:0,
 e:"Aktives Zuhören (nach Carl Rogers) meldet Inhalt UND Emotion zurück. Nebenbei Mails lesen ist Pseudo-Zuhören, „bei uns nie“ spielt herunter, „hätten Sie eben“ ist ein Vorwurf.",
 k:"Gesprächsführung",s:"LF3 3.2.3"},
{tg:2,g:"stress",src:"IZ Übung/16",t:"multi",
 q:"Welche zwei Maßnahmen gehören zur Stressprävention – also dazu, Stress gar nicht erst entstehen zu lassen?",
 a:["klare Ziele und Zuständigkeiten vereinbaren","den Arbeitsplatz ergonomisch einrichten","nach Feierabend Sport treiben","autogenes Training","eine Massage","Yoga-Übungen in der Pause"],cs:[0,1],
 e:"Stressprävention reduziert Stressoren (Zeitmanagement, klare Ziele, ergonomischer Arbeitsplatz, Konflikte früh klären). Stressbewältigung baut entstandenen Stress ab (Sport, Massage, Entspannungstechniken, Yoga). Stressoren können Eustress oder Disstress auslösen.",
 k:"Stimme & Stress",s:"LF3 6.2"},
{tg:2,g:"gespraechsabschluss",src:"IZ Übung/17",t:"order",
 q:"Bringen Sie die Schritte des Gesprächsabschlusses in die richtige Reihenfolge.",
 items:["Zielvereinbarung: Verbindlichkeit der Vereinbarung darstellen","das Wichtigste zusammenfassen","bei Bedarf einen Termin vereinbaren","Abschlussfrage mit Namen: „Kann ich sonst noch etwas für Sie tun, Herr Ralus?“","freundlich verabschieden","erst auflegen, wenn der Kunde aufgelegt hat"],
 e:"Die sechs Schritte laut Buch: Zielvereinbarung, Zusammenfassung, Terminvereinbarung, Abschlussfrage, Verabschiedung, Gesprächsende. Wer zuerst auflegt, wirkt ungeduldig oder unhöflich.",
 k:"Gesprächsführung",s:"LF5 1.1.4"},
{tg:2,g:"sichere-formulierung",src:"IZ Übung/18",t:"mc",
 q:"Welche Formulierung ist eine sichere Formulierung im Sinne des Buches?",
 a:["„Bitte nennen Sie mir Ihre Kundennummer.“","„Dürfte ich Sie vielleicht nach Ihrer Kundennummer fragen?“","„Ich würde vorschlagen, dass wir es mal versuchen.“","„Könnten Sie eventuell morgen noch einmal anrufen?“","„Ich werde versuchen, Ihnen das zu erklären.“"],c:0,
 e:"Sichere Formulierungen verzichten auf Konjunktive („dürfte“, „würde“, „könnten“) und Weichmacher wie „vielleicht“. „Ich werde versuchen, Ihnen das zu erklären“ hört der Kunde laut Buch als „Sie werden mich bestimmt nicht verstehen.“",
 k:"Gesprächsführung",s:"LF5 1.1.3"},
{tg:2,g:"beschwerde-reklamation",src:"IZ Übung/19",t:"mc",
 q:"Ein Kunde meldet einen Defekt an seinem vier Monate alten Headset und verlangt die Reparatur. Außerdem ärgert er sich über die unfreundliche Hotline. Welche Aussage trifft zu?",
 a:["Die verlangte Mangelbeseitigung ist eine Reklamation mit rechtlichem Anspruch; der Ärger über die Hotline ist eine Beschwerde.","Beides sind Reklamationen, weil der Kunde unzufrieden ist.","Beides sind Beschwerden ohne rechtlichen Hintergrund.","Eine Reklamation liegt nur vor, wenn der Kunde schriftlich reklamiert.","Die Unfreundlichkeit begründet einen Anspruch auf Mangelbeseitigung."],c:0,
 e:"Beschwerde = jede geäußerte Unzufriedenheit. Reklamation = zusätzlich ein rechtlicher Anspruch auf Mangelbeseitigung aus einer Kaufvertragsstörung. Oft gehen beide ineinander über; für die Gesprächsführung ist die Unterscheidung zunächst unerheblich.",
 k:"Beschwerden",s:"LF5 4.1.1"},
{tg:2,g:"haltegespraech",src:"IZ Übung/20",t:"order",
 q:"Eine Kundin möchte ihren Vertrag kündigen. Bringen Sie die Schritte des Haltegesprächs in die richtige Reihenfolge.",
 items:["in das Gespräch einsteigen und Bedauern ausdrücken","den Grund für die Kündigung mit offenen Fragen ermitteln","die emotionale Ebene klären","eine Lösung bzw. ein kulantes Angebot unterbreiten","das Gespräch abschließen"],
 e:"Im Haltegespräch wird das Produkt unter erschwerten Bedingungen neu verkauft. Widrigkeiten laut Buch: versteckte Kündigungsgründe, Einwände gegen die Lösung, unangemessene Forderungen – Kulanz endet beim wirtschaftlichen Prinzip (Kundenwert).",
 k:"Kundenbindung",s:"LF5 4.2"},
{tg:2,g:"aht",src:"IZ Übung/21",t:"calc",
 x:"Tagesauswertung Agentin Mia Kraft:\nbearbeitete Gespräche: 60\nGesprächszeit gesamt: 4 Stunden 10 Minuten\nNachbearbeitungszeit gesamt: 50 Minuten",
 q:"Berechnen Sie die AHT in Sekunden.",
 ans:["300"],unit:"Sekunden",
 e:"AHT = (Gesprächszeit + Nachbearbeitungszeit) / Anzahl Gespräche = (15.000 s + 3.000 s) / 60 = 300 s = 5 Minuten. Fehlerquelle: nur die Gesprächszeit nehmen (250 s). Probe: 60 · 300 s = 18.000 s = 5 Stunden.",
 k:"Kennzahlen",s:"LF5 5.1.1"},
{tg:2,g:"servicelevel-calc",src:"IZ Übung/22",t:"calc",
 x:"ACD-Report Service-Hotline, Montag:\nangenommene Anrufe gesamt: 1.250\ndavon innerhalb von 20 Sekunden angenommen: 1.050\nZielvorgabe: 80/20",
 q:"Welchen Servicelevel (in %) hat die Hotline erreicht?",
 ans:["84"],unit:"%",
 e:"1.050 · 100 / 1.250 = 84 % der Anrufe wurden innerhalb von 20 Sekunden angenommen → 84/20, die Vorgabe 80/20 ist erfüllt. Servicelevel 80/20 heißt: 80 % der Anrufe werden in höchstens 20 Sekunden angenommen – nicht „80 % Erfolg“.",
 k:"Kennzahlen",s:"LF5 5.1.2"},
{tg:2,g:"auslastung",src:"IZ Übung/23",t:"calc",
 x:"Agent Tom Weiß, Nettoarbeitszeit 7,5 Stunden:\nGesprächszeit 4,5 Stunden · Nachbearbeitungszeit 1,5 Stunden · Anrufwartezeit 1,5 Stunden",
 q:"Berechnen Sie Toms Auslastung (Occupancy).",
 ans:["80"],unit:"%",
 e:"Produktivzeit = Gesprächszeit + Nachbearbeitungszeit = 6 h. Auslastung = 6 · 100 / 7,5 = 80 % – laut Buch der angemessene Wert. Höhere Werte belasten die Agents dauerhaft, niedrigere verursachen unnötige Kosten. Wartezeit gehört nicht zur Produktivzeit.",
 k:"Kennzahlen",s:"LF5 5.1.4"},
{tg:2,g:"lcq",src:"IZ Übung/24",t:"calc",
 q:"An der Bestellhotline gingen 480 Anrufe ein, 456 wurden angenommen, die übrigen Anrufer legten vorher auf. Wie hoch ist die Lost-Call-Quote?",
 ans:["5"],unit:"%",
 e:"Aufgelegte Anrufe = 480 − 456 = 24. Lost-Call-Quote = 24 · 100 / 480 = 5 %. Bezugsgröße sind die eingehenden, nicht die angenommenen Anrufe (24 / 456 = 5,3 % wäre falsch). Ziel: möglichst nahe 0 %.",
 k:"Kennzahlen",s:"LF5 5.1.3"},
{tg:2,g:"fcr",src:"IZ Übung/25",t:"calc",
 q:"Von 390 bearbeiteten Anfragen im technischen Support konnten 351 bereits im ersten Kontakt gelöst werden. Wie hoch ist die First Call Resolution?",
 ans:["90"],unit:"%",
 e:"FCR = Lösungen beim Erstkontakt · 100 / bearbeitete Anfragen = 351 · 100 / 390 = 90 %. Eine hohe FCR steigert die Kundenzufriedenheit und senkt Kosten, weil Folgeanrufe entfallen.",
 k:"Kennzahlen",s:"LF5 5.1.5"},
{tg:2,g:"kreditkarten",src:"IZ Übung/26",t:"match",
 q:"Ordnen Sie die Beschreibungen dem Kartentyp zu.",
 pairs:[["Umsätze werden monatlich gesammelt und in einer Summe ohne Zinsen fällig.","Charge-Card"],["Umsätze können in Raten mit Zinsen zurückgezahlt werden – echte Kreditkarte.","Credit-Card"],["Jede Zahlung wird direkt vom Girokonto abgebucht.","Debit-Card"],["Die Karte muss vorab mit Guthaben aufgeladen werden.","Prepaid-Card"]],
 e:"In Deutschland ist die Charge-Card üblich (Kurzkredit ohne Zinsen), in den USA die Credit-Card. Die Debit-Card hat keine Kreditfunktion; die Prepaid-Card eignet sich für bonitätsschwache Kunden. Für Unternehmen: Zahlungsgarantie, aber Transaktionsgebühren.",
 k:"Zahlungsverkehr",s:"LF5 6.2"},
{tg:2,g:"zielkauf-finanzkauf",src:"IZ Übung/27",t:"mc",
 q:"Ein Kunde möchte sein neues Notebook „in 30 Tagen auf einmal“ bezahlen, eine andere Kundin „in 24 Monatsraten“. Welche Zuordnung ist richtig?",
 a:["Kunde: Zielkauf (Zahlungsziel), meist kostenfrei · Kundin: Finanzkauf (Ratenzahlung) mit Zinsen und Gebühren","Kunde: Finanzkauf · Kundin: Zielkauf","beide: Zielkauf, weil beide später zahlen","beide: Finanzkauf, weil beide einen Kredit erhalten","Kunde: Vorauskasse · Kundin: Nachnahme"],c:0,
 e:"Zielkauf = Zahlung des Gesamtbetrags zu einem späteren Termin, 7–30 Tage meist kostenfrei. Finanzkauf = Ratenzahlung über z. B. 6–72 Monate mit Zinsen und Bearbeitungsgebühren. Beide setzen ausreichende Bonität voraus.",
 k:"Zahlungsverkehr",s:"LF5 6.2"},
{tg:2,g:"iban",src:"IZ Übung/28",t:"mc",
 q:"Wie ist eine deutsche IBAN aufgebaut?",
 a:["DE + 2-stellige Prüfziffer + 8-stellige Bankleitzahl + 10-stellige Kontonummer","DE + 8-stellige Kontonummer + 10-stellige Bankleitzahl","BIC + Kontonummer","2-stellige Prüfziffer + DE + Kontonummer + BIC","DE + Postleitzahl der Bank + Kontonummer"],c:0,
 e:"IBAN (International Bank Account Number) Deutschland: Länderkennung DE, 2 Prüfziffern, 8 Stellen Bankleitzahl, 10 Stellen Kontonummer = 22 Zeichen. Der BIC identifiziert dagegen die Bank weltweit. SEPA: Überweisung in einem Bankgeschäftstag, 8 Wochen Widerspruchsfrist bei Lastschriften.",
 k:"Zahlungsverkehr",s:"LF5 6.2"},
{tg:2,g:"versand-haftung",src:"IZ Übung/29",t:"mc",
 q:"Ein Kunde meldet, dass sein Zubehör, das als DHL-Päckchen verschickt wurde, nicht angekommen ist. Was gilt?",
 a:["Für Päckchen haftet DHL nicht – anders als für Pakete (bis 500 €).","DHL haftet für Päckchen bis 500 €.","DHL haftet für Päckchen pauschal mit 25 €.","DHL haftet unbegrenzt.","Es haftet grundsätzlich der Empfänger."],c:0,
 e:"Laut Buch haftet DHL bei Paketen ohne Zusatzversicherung bis 500 €, bei Einschreiben pauschal mit 25 €. Keine Haftung bei Päckchen, Bücher- und Warensendungen, bei Schäden durch den Versender oder bei verspäteter Schadensmeldung. Wertvolles also als Paket oder versichert versenden.",
 k:"Versand",s:"LF5 7.3"},
{tg:2,g:"kundenlebenszyklus",src:"IZ Übung/30",t:"order",
 q:"Bringen Sie die Phasen des Kundenlebenszyklus in die richtige Reihenfolge.",
 items:["Akquisitionsphase","Angebotsphase","Kaufphase","After-Sales-Phase","Betreuungsphase","Optimierungsphase"],
 e:"Der Kauf liegt in der Mitte des Zyklus – danach folgen After-Sales (Fragen, Reklamationen direkt nach dem Kauf), langfristige Betreuung und Optimierung. CRM richtet alle Unternehmensbereiche auf diese langfristige Beziehung aus.",
 k:"CRM",s:"LF5 3.1.2"},
{tg:2,g:"crm-saeulen",src:"IZ Übung/31",t:"multi",
 q:"Welche zwei Aufgabenfelder gehören zu den drei Säulen des CRM im Dialogmarketing?",
 a:["Neukundengewinnung","Kundenrückgewinnung (Winback)","Lagerhaltung","Buchhaltung","Personalbeschaffung","Produktion"],cs:[0,1],
 e:"Die drei Säulen des CRM: Bestandskundenpflege, Neukundengewinnung und Kundenrückgewinnung. CRM ist laut Buch die Strategie, alle Unternehmensbereiche auf langfristige Kundenbeziehungen auszurichten.",
 k:"CRM",s:"LF5 3.1.1"},
{tg:2,g:"storno",src:"IZ Übung/32",t:"calc",
 q:"Nach einer Outbound-Aktion liegen 640 Aufträge vor. Innerhalb der Widerrufsfrist werden 96 storniert. Wie hoch ist die Stornoquote?",
 ans:["15"],unit:"%",
 e:"Stornoquote = Stornos · 100 / Gesamtaufträge = 96 · 100 / 640 = 15 %. Die gesetzliche Widerrufsfrist beträgt zwei Wochen. Eine hohe Stornoquote kann auf Produktmängel oder nicht bedarfsgerechte Gesprächsführung hinweisen.",
 k:"Kennzahlen",s:"LF5 5.2.3"},

/* ── Themengebiet 3 ─────────────────────────────────────────────── */
{tg:3,g:"ani-dnis",src:"IZ Übung/33",t:"mc",
 q:"Die Dialog-GmbH betreut zwei Kunden über zwei verschiedene 0800-Nummern auf derselben Anlage. Welcher Dienst erkennt, welche der beiden Nummern der Anrufer gewählt hat?",
 a:["DNIS (Dialed Number Identification Service)","ANI (Automatic Number Identification)","IVR (Interactive Voice Response)","Predictive Dialer","Call Blending"],c:0,
 e:"DNIS erkennt die gewählte Nummer und ermöglicht so die Zuordnung zum Projekt. ANI übermittelt dagegen die Rufnummer des Anrufers (z. B. für das Öffnen des Kundendatensatzes per CTI). Klassisches Verwechslungspaar!",
 k:"Branchentechnik",s:"LF4 1.2.1"},
{tg:3,g:"acd-ivr-cti",src:"IZ Übung/34",t:"match",
 q:"Ordnen Sie die Funktionen der passenden Technik zu.",
 pairs:[["Sprachcomputer, der Anrufer per Tastenwahl oder Sprache vorsortiert","IVR"],["verteilt eingehende Anrufe auf freie Agents","ACD"],["öffnet beim Anruf automatisch den Kundendatensatz (Screen-Pop-up)","CTI"],["schaltet Inbound-Agents in ruhigen Zeiten auf Outbound um","Call Blending"]],
 e:"ACD = Kernstück der TK-Anlage (Routing, Reporting, Echtzeitmanagement). IVR = Sprachdialogsystem zur Vorselektion. CTI = Verschmelzung von Telefon, Computer und Datenbank. Call Blending = Mischung von In- und Outbound (Swinging Agents).",
 k:"Branchentechnik",s:"LF4 1.2.2"},
{tg:3,g:"dialer",src:"IZ Übung/35",t:"mc",
 q:"Bei welchem Dialer wählt das System erst, nachdem der Agent die Anwahl bestätigt hat, sodass er sich vorher auf den Kunden vorbereiten kann?",
 a:["Preview Dialing","Power Dialing","Predictive Dialing","Call Blending","Overflow"],c:0,
 e:"Preview Dialing = Wahlhilfe nach Bestätigung durch den Agent (kaum Produktivitätsgewinn). Power Dialing wählt automatisch und stellt nur freien Agents Gespräche zu. Predictive Dialing berechnet per Forecasting, wie viele Anwahlen nötig sind – höchste Produktivität, aber Risiko von Silent Calls.",
 k:"Branchentechnik",s:"LF4 1.2.5"},
{tg:3,g:"dialer",src:"IZ Übung/36",t:"mc",
 q:"Ein Kunde beschwert sich: Sein Telefon klingelt, er hebt ab – aber niemand meldet sich. Was ist die typische Ursache?",
 a:["Ein Silent Call: Der Predictive Dialer hat mehr Nummern angewählt, als Agents frei waren, und das Gespräch verworfen.","Die IVR ist ausgefallen.","Der Kunde hat eine 0900-Nummer gewählt.","Das Gespräch wurde per Skill Based Routing weitergeleitet.","Die Firewall hat das Gespräch blockiert."],c:0,
 e:"Durch die Overdial-Funktion wählen Power- und Predictive Dialer mehr Nummern an, als Agents frei sind. Ist kein Agent verfügbar, wird der erreichte Kunde „gedropt“ – ein Silent Call. Massenhafte Anrufe dieser Art verstoßen gegen das UWG; die Bundesnetzagentur kann Rufnummern abschalten.",
 k:"Branchentechnik",s:"LF4 1.2.5"},
{tg:3,g:"pop3-imap",src:"IZ Übung/37",t:"mc",
 q:"Sie möchten Ihre dienstlichen E-Mails auf PC, Tablet und Smartphone jeweils auf demselben Stand sehen. Welches Protokoll ist dafür geeignet?",
 a:["IMAP","POP3","SMTP","FTP","HTTP"],c:0,
 e:"Bei IMAP bleiben die Mails auf dem Server und werden auf allen Geräten synchronisiert. POP3 holt die Mails ab und löscht sie meist auf dem Server. SMTP dient dem Versenden, FTP dem Dateitransfer, HTTP der Übertragung von Webseiten.",
 k:"Netze & Dienste",s:"LF4 1.1.6"},
{tg:3,g:"virus-wurm",src:"IZ Übung/38",t:"mc",
 q:"Worin unterscheidet sich ein Wurm von einem Virus?",
 a:["Der Wurm verbreitet sich selbstständig über Netzwerke, der Virus braucht ein Wirtsprogramm.","Der Virus verbreitet sich selbstständig, der Wurm braucht ein Wirtsprogramm.","Der Wurm verschlüsselt Dateien und verlangt Lösegeld.","Der Wurm ist harmlos, weil er keine Dateien befällt.","Es gibt keinen Unterschied."],c:0,
 e:"Virus: befällt Programmdateien und vermehrt sich nur über andere Programme (Wirt). Wurm: „Netzwerk-Virus“, befällt keine Dateien, verbreitet sich selbstständig und beansprucht Rechenzeit. Lösegeld verlangt Ransomware.",
 k:"Datensicherheit",s:"LF4 5.1"},
{tg:3,g:"malware",src:"IZ Übung/39",t:"match",
 q:"Ordnen Sie die Beschreibungen der passenden Bedrohung zu.",
 pairs:[["Eine gefälschte Bank-Mail fordert per Link zur Eingabe von Zugangsdaten auf.","Phishing"],["Dateien werden verschlüsselt, für die Freigabe wird Lösegeld verlangt.","Ransomware"],["Ein Programm sammelt heimlich Surfgewohnheiten und sendet sie ins Internet.","Spyware"],["Eine scheinbar nützliche Gratis-App stiehlt im Hintergrund Passwörter.","Trojaner"],["Eine Kettenmail warnt vor einem angeblichen Virus und bittet ums Weiterleiten.","Hoax"]],
 e:"Phishing = Password + Fishing. Ransom = Lösegeld. Spyware = Spionagesoftware. Trojaner geben vor, harmlos zu sein. Hoax = Falschmeldung („Ente“), die Panik und Weiterleiten auslösen soll.",
 k:"Datensicherheit",s:"LF4 5.1"},
{tg:3,g:"backup",src:"IZ Übung/40",t:"match",
 q:"Ordnen Sie die Beschreibungen der passenden Backup-Art zu.",
 pairs:[["sichert alle Daten 1:1","Voll-Backup"],["sichert nur die Änderungen seit dem letzten inkrementellen Backup","inkrementelles Backup"],["sichert alle Änderungen seit dem letzten Voll-Backup","differenzielles Backup"],["sichert täglich die wichtigsten Dateien eines Verzeichnisses auf wechselnden Medien","partielles Backup"]],
 e:"Das Voll-Backup braucht viel Speicher. Inkrementelle Sicherungen sind klein, aber ohne das Voll-Backup wertlos. Differenzielle Sicherungen wachsen bis zum nächsten Voll-Backup. Verwechslungsgefahr: inkrementell (seit letzter Teilsicherung) ↔ differenziell (seit letzter Vollsicherung).",
 k:"Datensicherheit",s:"LF4 5.2.7"},
{tg:3,g:"firewall",src:"IZ Übung/41",t:"mc",
 q:"Welche Aussage zu Firewalls trifft zu?",
 a:["Eine Personal-Firewall ist Software auf dem einzelnen PC, eine Netzwerk-Firewall ist Hardware im Firmennetz.","Eine Firewall erkennt und entfernt Viren in Dateien.","Eine Personal-Firewall schützt das gesamte Firmennetz.","Eine Firewall ersetzt die Datensicherung.","Eine Firewall verschlüsselt E-Mails."],c:0,
 e:"Die Firewall regelt, kontrolliert und protokolliert den Datenverkehr zwischen zwei Netzen („Türsteher“). Personal-Firewall = Software auf dem PC, Netzwerk-Firewall = Hardware im großen Netz. Viren entfernt das Antivirenprogramm.",
 k:"Datensicherheit",s:"LF4 5.2.3"},
{tg:3,g:"primaerschluessel",src:"IZ Übung/42",t:"mc",
 q:"Welche Spalte der Tabelle „Kunden“ eignet sich als Primärschlüssel?",
 a:["Kundennummer","Nachname","Postleitzahl","Geburtsdatum","Wohnort"],c:0,
 e:"Der Primärschlüssel identifiziert jeden Datensatz eindeutig – sein Inhalt kommt nur einmal vor (z. B. Kundennummer), üblicherweise in der ersten Spalte. Namen, PLZ, Geburtsdaten oder Orte können mehrfach vorkommen. Ein Fremdschlüssel ist der Primärschlüssel einer anderen Tabelle.",
 k:"Datenbanken",s:"LF4 4.3"},
{tg:3,g:"datenhierarchie",src:"IZ Übung/43",t:"order",
 q:"Bringen Sie die Begriffe der Datenhierarchie in die richtige Reihenfolge – von der kleinsten zur größten Einheit.",
 items:["Datenfeld","Datensatz","Datei","Datenbank"],
 e:"Datenfeld (z. B. Kundennummer „658741“) → Datensatz (alle Felder eines Kunden) → Datei (alle Kundendatensätze, in der relationalen DB eine Tabelle) → Datenbank (verknüpfte Dateien).",
 k:"Datenbanken",s:"LF4 4.3"},
{tg:3,g:"omnichannel",src:"IZ Übung/44",t:"mc",
 q:"Ein Kunde beginnt eine Anfrage im Chat und setzt sie später am Telefon fort, ohne etwas wiederholen zu müssen. Welches Konzept liegt vor?",
 a:["Omnichannel","Multichannel","Call Blending","Outsourcing","Preview Dialing"],c:0,
 e:"Omnichannel: Alle Kanäle sind verfügbar UND miteinander vernetzt – nahtloses Kundenerlebnis. Multichannel: mehrere Kanäle ohne vollständige Vernetzung. Grundlage ist Customer Centricity (Kunde im Mittelpunkt).",
 k:"Branchentechnik",s:"LF4 1.2.6"},
{tg:3,g:"tkg-warteschleife",src:"IZ Übung/45",t:"mc",
 q:"Warum wurden mit der TKG-Novelle 2013 die Rufnummerngassen 01806 und 01807 eingeführt?",
 a:["Weil Warteschleifen seitdem für den Anrufer kostenlos sein müssen.","Weil 0800-Nummern abgeschafft wurden.","Weil Televoting nur noch über 0180 laufen darf.","Weil 0900-Nummern keine Preisansage mehr brauchen.","Weil Mobilfunkanrufe kostenlos wurden."],c:0,
 e:"Seit der TKG-Novelle 2013 dürfen Warteschleifen – Zeiten, in denen das Anliegen nicht bearbeitet wird – nichts kosten. Daher: 01806 (Festpreis pro Anruf) und 01807 (erste 30 Sekunden kostenlos). 0900 = Premium-Dienste mit Preisansage, 0800 = Freecall.",
 k:"Netze & Dienste",s:"LF4 3.2"},
{tg:3,g:"suchoperator",src:"IZ Übung/46",t:"mc",
 q:"Mit welcher Eingabe findet eine Suchmaschine nur Seiten, die die Wörter genau in dieser Reihenfolge enthalten?",
 a:["\"Handy Datenblatt\"","Handy -Datenblatt","Handy +Datenblatt","define:Handy","Handy filetype:pdf"],c:0,
 e:"Anführungszeichen = exakte Wortfolge. Minus = Begriff ausschließen, Plus = Begriff muss enthalten sein, define: = Begriffsdefinition, filetype: = bestimmter Dateityp.",
 k:"Netze & Dienste",s:"LF4 3.4"},
{tg:3,g:"eisenhower",src:"IZ Übung/47",t:"match",
 q:"Ordnen Sie den Aufgabentypen nach dem Eisenhower-Prinzip die richtige Behandlung zu.",
 pairs:[["wichtig und dringend","sofort selbst erledigen"],["wichtig, aber nicht dringend","terminieren und selbst erledigen"],["dringend, aber nicht wichtig","delegieren"],["weder wichtig noch dringend","Papierkorb"]],
 e:"Eisenhower ordnet Aufgaben nach Wichtigkeit und Dringlichkeit in vier Felder (A bis D). D-Aufgaben dürfen laut Buch „mit gutem Gewissen in den Papierkorb wandern“ – als bewusste Entscheidung.",
 k:"Information & Lernen",s:"LF1 6.1"},
{tg:3,g:"alpen",src:"IZ Übung/48",t:"calc",
 q:"Sie planen Ihren 8-Stunden-Arbeitstag nach der ALPEN-Methode mit der 60/40-Regel. Wie viele Stunden verplanen Sie fest mit Aufgaben?",
 ans:["4,8"],unit:"Stunden",
 e:"ALPEN: Aufgaben notieren, Länge schätzen, Pufferzeiten einplanen, Entscheidungen treffen, Nachkontrolle. 60/40-Regel: 60 % der Zeit verplanen, 40 % als Puffer → 8 h · 0,6 = 4,8 h (4 h 48 min). Probe: 4,8 h + 3,2 h Puffer = 8 h.",
 k:"Information & Lernen",s:"LF1 6.1"},
{tg:3,g:"protokollart",src:"IZ Übung/49",t:"mc",
 q:"Nach der Teambesprechung sollen nur die gefassten Beschlüsse kurz festgehalten werden. Welche Protokollart wählen Sie?",
 a:["Ergebnisprotokoll","Verlaufsprotokoll","Gesprächsleitfaden","Sendeprotokoll","Reporting"],c:0,
 e:"Das Ergebnisprotokoll hält nur Ergebnisse und Beschlüsse fest und ist kürzer. Das Verlaufsprotokoll dokumentiert zusätzlich den Ablauf mit Beiträgen und Diskussion.",
 k:"Information & Lernen",s:"LF1 5.1"},
{tg:3,g:"informationskanal",src:"IZ Übung/50",t:"mc",
 q:"Eine Teamleiterin muss einem Mitarbeiter mitteilen, dass seine Leistungen deutlich nachgelassen haben. Welchen Informationskanal wählt sie?",
 a:["ein Einzelgespräch","eine Rundmail an das Team","einen Beitrag im Intranet","einen Punkt im Teammeeting","einen Aushang am Schwarzen Brett"],c:0,
 e:"Sensible, kritische und persönliche Themen gehören ins Einzelgespräch. Intranet und Rundmail eignen sich für Informationen an alle, Meetings für komplexe Themen mit Diskussion.",
 k:"Information & Lernen",s:"LF1 5.1"},
{tg:3,g:"laerm-klima",src:"IZ Übung/51",t:"mc",
 q:"Welche Werte gelten laut Buch als Richtwerte für einen Callcenter-Arbeitsplatz?",
 a:["Lärm höchstens 2 sone, Lufttemperatur 20–23 °C, Luftfeuchtigkeit 50–60 %","Lärm höchstens 8 sone, Lufttemperatur 26–28 °C, Luftfeuchtigkeit 20–30 %","Lärm höchstens 2 Dezibel, Lufttemperatur 17 °C, Luftfeuchtigkeit 80 %","Lärm unbegrenzt, solange Headsets getragen werden","Lärm höchstens 4 sone, Lufttemperatur 15–18 °C"],c:0,
 e:"Sone misst das subjektive Lautheitsempfinden (2 sone = normale Unterhaltung, doppelt so laut wie 1 sone); Dezibel misst den Schalldruck. Ab etwa 26 °C sinkt die Leistungsfähigkeit.",
 k:"Arbeitsplatz",s:"LF1 4.3"},
{tg:3,g:"management-by",src:"IZ Übung/52",t:"match",
 q:"Ordnen Sie die Beschreibungen der passenden Führungstechnik zu.",
 pairs:[["Ziele werden gemeinsam vereinbart und nach Ablauf überprüft.","Management by objectives"],["Mitarbeiter entscheiden Routinefälle selbst, die Führung greift nur bei Ausnahmen ein.","Management by exception"],["Die Führung gibt Kennzahlen verbindlich vor und prüft Soll gegen Ist.","Management by results"],["Klar abgegrenzte Aufgaben werden mit Entscheidungskompetenz übertragen.","Management by delegation"]],
 e:"Führungstechniken sind organisatorische Techniken – nicht zu verwechseln mit Führungsstilen (autoritär, kooperativ, Laissez-faire, situativ). Buchbeispiel exception: Gutschriften bis 20 € entscheidet der Mitarbeiter selbst.",
 k:"Führung",s:"LF1 1.1.3"},
{tg:3,g:"smart",src:"IZ Übung/53",t:"mc",
 q:"Wofür steht das „A“ in der SMART-Regel zur Zielformulierung laut Buch?",
 a:["aktiv beeinflussbar","angemessen bezahlt","abteilungsübergreifend","anonym","automatisch"],c:0,
 e:"SMART: spezifisch, messbar, aktiv beeinflussbar, realistisch, terminiert. Die Regel wird beim Management by objectives genutzt. Andere Quellen deuten das A teils anders – maßgeblich ist hier der Buchwortlaut.",
 k:"Führung",s:"LF1 1.1.3"},
{tg:3,g:"zielbeziehung",src:"IZ Übung/54",t:"mc",
 q:"Die Dialog-GmbH will nur noch teures Recyclingpapier mit Umweltsiegel einsetzen, gleichzeitig soll die Rentabilität steigen. Welche Zielbeziehung liegt vor?",
 a:["Zielkonflikt","Zielharmonie","Zielneutralität","Sachziel","Zielvereinbarung"],c:0,
 e:"Zielkonflikt: Ein Ziel (ökologisch) ist nur erreichbar, wenn ein anderes (wirtschaftlich) beeinträchtigt wird. Lösung: Priorisierung oder Kompromiss. Zielharmonie: Ziele ergänzen sich, z. B. Umsatzwachstum sichert Arbeitsplätze.",
 k:"Entscheidungsmethoden",s:"LF1 1.1.1"},
{tg:3,g:"pmi",src:"IZ Übung/55",t:"mc",
 q:"Ein Teamleiter markiert alle Aspekte einer Entscheidung mit „+“, „–“ oder „i“ (interessant). Welche Methode nutzt er?",
 a:["PMI (Plus-Minus-Interesting)","CAF (Consider all Facts)","gewichtete Entscheidungsmatrix","intuitive Entscheidung","Pareto-Prinzip"],c:0,
 e:"CAF sammelt nur alle Faktoren ungewichtet; PMI ordnet sie zusätzlich als Plus, Minus oder interessant ein; das gewichtete PMI vergibt Punkte. Die Entscheidungsmatrix bewertet mehrere Alternativen nach Kriterien.",
 k:"Entscheidungsmethoden",s:"LF1 1.1.2"},
{tg:3,g:"verstaendlichmacher",src:"IZ Übung/56",t:"mc",
 q:"Ihre Folie enthält lange Schachtelsätze und viele Fremdwörter. Gegen welchen Verständlichmacher nach Schulz von Thun verstößt sie vor allem?",
 a:["Einfachheit","Gliederung","Prägnanz","Stimulanz","Appell"],c:0,
 e:"Die vier Verständlichmacher: Einfachheit (kurze Sätze, Wortschatz der Zielgruppe), Gliederung (logische Struktur), Prägnanz (Wesentliches in wenigen Worten), Stimulanz (Farben, Beispiele). Der Appell ist eine Seite der Nachricht (Vier-Ohren-Modell).",
 k:"Präsentation",s:"LF2 3.2"},
{tg:3,g:"datenkategorien",src:"IZ Übung/57",t:"match",
 q:"Ordnen Sie die Kundendaten der passenden Datenkategorie zu.",
 pairs:[["Geburtsdatum und Anschrift","Grunddaten"],["Anzahl der Beschwerden im letzten Jahr","Aktionsdaten"],["Durchschnittsumsatz je Bestellung","Ergebnisdaten"],["Reaktion auf das letzte Mailing","Aktionsdaten"]],
 e:"Grunddaten: Wer ist der Kunde? (Adresse, Soziodemografie, Bonität – auch Stammdaten genannt). Aktionsdaten: Was passierte wann? (Kontakte, Reaktionen, Beschwerden, Retouren). Ergebnisdaten: Welche Ergebnisse? (Umsatz, Kaufhäufigkeit, Zahlverhalten).",
 k:"Datenmanagement",s:"LF5 2.1"},
{tg:3,g:"datenpflege",src:"IZ Übung/58",t:"mc",
 q:"Welche Maßnahme zur Pflege von Bestandskundendaten ist laut Buch die günstigste und effizienteste?",
 a:["der interne Abgleich bei jedem Kundenkontakt","der externe Abgleich durch einen Dienstleister","eine eigene Outbound-Aktion nur zur Datenprüfung","das Löschen aller Kunden nach einem Jahr","der Kauf neuer Adressen beim Adressbroker"],c:0,
 e:"Pflegemaßnahmen laut Buch: Bereinigung (inaktive Kunden löschen), externer Abgleich, interner Abgleich und Abgleich per Outbound. Der interne Abgleich nutzt jeden ohnehin stattfindenden Kontakt – z. B. beim Sicherheitsabgleich zu Gesprächsbeginn.",
 k:"Datenmanagement",s:"LF5 2.3"},

/* ── Themengebiet 4 ─────────────────────────────────────────────── */
{tg:4,g:"kaufmannsarten",src:"IZ Übung/59",t:"match",
 q:"Ordnen Sie die Beschreibungen der passenden Kaufmannsart zu.",
 pairs:[["betreibt ein Handelsgewerbe; die Eintragung im Handelsregister wirkt nur rechtsbezeugend","Istkaufmann"],["Kleingewerbetreibender, der erst durch freiwillige Eintragung Kaufmann wird","Kannkaufmann"],["GmbH, die kraft ihrer Rechtsform Kaufmann ist","Formkaufmann"]],
 e:"Istkaufmann: Eintragung deklaratorisch (bezeugt eine schon bestehende Eigenschaft). Kannkaufmann und Formkaufmann: Eintragung konstitutiv (begründet die Kaufmannseigenschaft erst). Freie Berufe (Ärzte, Anwälte) betreiben kein Handelsgewerbe.",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"firmengrundsatz",src:"IZ Übung/60",t:"mc",
 q:"In derselben Stadt soll ein zweites Unternehmen unter dem Namen „Dialogfix GmbH“ eingetragen werden. Gegen welchen Grundsatz der Firmenwahl verstößt das?",
 a:["Firmenausschließlichkeit","Firmenbeständigkeit","Firmenöffentlichkeit","Firmenwahrheit und -klarheit","Rechtsformzusatz"],c:0,
 e:"Firmenausschließlichkeit: Eine Firma muss sich am selben Ort deutlich von anderen unterscheiden. Wahrheit/Klarheit: keine irreführenden Angaben; Beständigkeit: Firma nur zusammen mit dem Handelsgeschäft übertragbar; Öffentlichkeit: Eintragung und Angabe auf Geschäftsbriefen; Rechtsformzusatz legt die Haftung offen.",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"firmenarten",src:"IZ Übung/61",t:"match",
 q:"Ordnen Sie die Firmen der passenden Firmenart zu.",
 pairs:[["Weber & Hansen KG","Personenfirma"],["Telefonservice Nord GmbH","Sachfirma"],["Zyxora GmbH","Fantasiefirma"],["Lena Brandt Kundenservice e. K.","Mischfirma"]],
 e:"Personenfirma = Name eines oder mehrerer Inhaber/Gesellschafter; Sachfirma = beschreibt den Gegenstand des Unternehmens; Fantasiefirma = frei erfunden (Buch: Dialogfix GmbH); Mischfirma = Kombination aus Person und Sache. „Firma“ ist der Name, unter dem der Kaufmann Geschäfte betreibt – nicht das Unternehmen selbst.",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"hr-abteilung",src:"IZ Übung/62",t:"mc",
 q:"In welcher Abteilung des Handelsregisters wird eine GmbH eingetragen?",
 a:["Abteilung B","Abteilung A","Abteilung C","Sie wird nicht eingetragen.","im Gewerberegister statt im Handelsregister"],c:0,
 e:"Abteilung A (HRA): Einzelkaufleute und Personengesellschaften (z. B. KG). Abteilung B (HRB): Kapitalgesellschaften (z. B. GmbH). Das Register wird elektronisch beim Amtsgericht geführt; Eintragungen genießen öffentlichen Glauben.",
 k:"Recht",s:"LF1 1.3.1"},
{tg:4,g:"leitungssystem",src:"IZ Übung/63",t:"mc",
 q:"Eine Agentin erhält Weisungen sowohl von ihrer Teamleiterin als auch direkt von der Qualitätsmanagerin und der IT-Leitung. Welches Leitungssystem liegt vor?",
 a:["Mehrlinienorganisation","Einlinienorganisation","Stablinienorganisation","Spartenorganisation","Ablauforganisation"],c:0,
 e:"Mehrlinienorganisation: Aufträge kommen nach Aufgabentyp von mehreren Stellen – kurze Wege, aber Gefahr widersprüchlicher Anweisungen. Einlinie: nur eine übergeordnete Instanz. Stablinie: Einlinie mit beratenden Stabsstellen ohne (disziplinarische) Weisungsbefugnis.",
 k:"Organisation",s:"LF1 1.2.2"},
{tg:4,g:"gmbh-co-kg",src:"IZ Übung/64",t:"mc",
 q:"Was kennzeichnet eine GmbH & Co. KG?",
 a:["Sie ist rechtlich eine KG, deren einziger Komplementär eine GmbH ist.","Sie ist eine GmbH, deren Gesellschafter unbeschränkt haften.","Sie ist eine KG ohne Kommanditisten.","Sie ist eine Kapitalgesellschaft mit Mindestkapital 50.000 €.","Sie ist eine GmbH, die im Handelsregister Abteilung A steht."],c:0,
 e:"Bei der GmbH & Co. KG übernimmt eine GmbH die Rolle des Vollhafters. Die unmittelbare, unbeschränkte Haftung des Komplementärs wird so zu einer mittelbaren, beschränkten Haftung.",
 k:"Recht",s:"LF1 1.3.3"},
{tg:4,g:"probezeit-dauer",src:"IZ Übung/65",t:"mc",
 q:"Wie lang muss die Probezeit in einem Berufsausbildungsverhältnis nach § 20 BBiG sein?",
 a:["mindestens einen Monat, höchstens vier Monate","mindestens drei, höchstens sechs Monate","genau sechs Monate","höchstens zwei Wochen","Sie kann frei vereinbart werden."],c:0,
 e:"Die Probezeit dauert mindestens einen und höchstens vier Monate. In dieser Zeit können beide Seiten jederzeit ohne Frist und ohne Grund kündigen – schriftlich. Die Paragrafenangabe (§ 20 BBiG) ist ergänzt aus dem Gesetz; das Buch behandelt die Probezeit bei der Beendigung (§ 22 BBiG).",
 k:"BBiG",s:"LF1 2.1.4"},
{tg:4,g:"weiterbeschaeftigung",src:"IZ Übung/66",t:"mc",
 q:"Lara hat ihre Abschlussprüfung bestanden. Am nächsten Tag arbeitet sie wie gewohnt weiter, ohne dass etwas vereinbart wurde. Was gilt nach § 24 BBiG?",
 a:["Es entsteht automatisch ein unbefristetes Arbeitsverhältnis.","Es entsteht ein auf sechs Monate befristetes Arbeitsverhältnis.","Lara arbeitet weiter als Auszubildende.","Das Arbeitsverhältnis entsteht erst mit einem schriftlichen Vertrag.","Lara muss eine neue Probezeit absolvieren, bevor ein Vertrag entsteht."],c:0,
 e:"Wird ein Auszubildender im Anschluss an die Ausbildung beschäftigt, ohne dass etwas vereinbart ist, gilt ein Arbeitsverhältnis auf unbestimmte Zeit als begründet – ohne ausdrückliche Vereinbarung. Die Ausbildung endet mit Bekanntgabe des Prüfungsergebnisses.",
 k:"BBiG",s:"LF1 2.1.4"},
{tg:4,g:"ausbildender-pflichten",src:"IZ Übung/67",t:"multi",
 q:"Welche zwei Pflichten hat der Ausbildende gegenüber der Auszubildenden?",
 a:["Ausbildungsmittel kostenlos zur Verfügung stellen","für den Besuch der Berufsschule freistellen","die Weisungen der Auszubildenden befolgen","die Berufsschulnoten an die Eltern melden","eine Übernahme nach der Ausbildung garantieren","Überstunden unbegrenzt anordnen"],cs:[0,1],
 e:"Pflichten des Ausbildenden: Handlungsfähigkeit vermitteln, kostenlose Arbeitsmittel, Freistellung für Berufsschule und Prüfungen, Urlaub gewähren, Fürsorge, angemessene und jährlich steigende Vergütung, Zeugnis. Pflichten der Auszubildenden: lernen, sorgfältig arbeiten, Weisungen befolgen, Schweigepflicht u. a.",
 k:"BBiG",s:"LF1 2.1.3"},
{tg:4,g:"jarbschg-pause",src:"IZ Übung/68",t:"calc",
 q:"Der 16-jährige Auszubildende Jonas arbeitet heute 7 Stunden. Wie lang müssen seine Ruhepausen nach dem JArbSchG insgesamt mindestens sein?",
 ans:["60"],unit:"Minuten",
 e:"JArbSchG: 30 Minuten bei mehr als 4,5 bis 6 Stunden, 60 Minuten bei mehr als 6 Stunden Arbeitszeit. Pausen zählen nur ab 15 Minuten, frühestens 1 Stunde nach Beginn und spätestens 1 Stunde vor Ende; höchstens 4,5 Stunden am Stück ohne Pause. Für Erwachsene gilt das ArbZG (30 Minuten ab 6 Stunden).",
 k:"Schutzgesetze",s:"LF1 2.2.1"},
{tg:4,g:"jarbschg-freizeit",src:"IZ Übung/69",t:"type",
 q:"Die 17-jährige Auszubildende Emma beendet ihre Arbeit heute um 19:30 Uhr. Wann darf sie morgen frühestens wieder beschäftigt werden? (Uhrzeit hh:mm)",
 ans:["07:30","7:30","07.30","7.30","0730"],unit:"Uhr",
 e:"Nach Arbeitsende steht Jugendlichen eine ununterbrochene Freizeit von mindestens 12 Stunden zu: 19:30 Uhr + 12 h = 07:30 Uhr. Zusätzlich gilt: Beschäftigung nur zwischen 6 und 20 Uhr – 7:30 Uhr liegt innerhalb dieses Rahmens.",
 k:"Schutzgesetze",s:"LF1 2.2.1"},
{tg:4,g:"br-rechte-stufen",src:"IZ Übung/70",t:"match",
 q:"Ordnen Sie die Maßnahmen der Geschäftsleitung dem passenden Beteiligungsrecht des Betriebsrats zu.",
 pairs:[["kurzfristige Anordnung von Überstunden","Mitbestimmungsrecht"],["Versetzung eines Agents in eine andere Abteilung","Mitwirkungsrecht"],["Investition in einen neuen Standort","Informations- und Beratungsrecht"],["Einführung eines Monitoring-Systems für Gespräche","Mitbestimmungsrecht"]],
 e:"Mitbestimmung (stärkstes Recht, ohne Zustimmung unwirksam): Arbeitszeit, Pausen, Gesundheitsschutz, Arbeitskontrollen/Monitoring, Überstunden. Mitwirkung (Anhörung, Widerspruch): personelle Einzelmaßnahmen wie Einstellung und Versetzung – ab 20 wahlberechtigten Arbeitnehmern. Information/Beratung: wirtschaftliche Angelegenheiten.",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:4,g:"br-kuendigung",src:"IZ Übung/71",t:"mc",
 q:"Die Geschäftsleitung kündigt einem Mitarbeiter, ohne den Betriebsrat vorher anzuhören. Welche Folge hat das nach § 102 BetrVG?",
 a:["Die Kündigung ist unwirksam.","Die Kündigung ist wirksam, der Betriebsrat erhält eine Entschädigung.","Die Kündigung wird automatisch in eine Abmahnung umgewandelt.","Der Betriebsrat muss die Kündigung nachträglich genehmigen, sonst ist sie verjährt.","Es hat keine Folge, die Anhörung ist freiwillig."],c:0,
 e:"Vor jeder Kündigung ist der Betriebsrat anzuhören – sonst ist die Kündigung unwirksam. Widerspricht der Betriebsrat einer ordentlichen Kündigung, bleibt sie dennoch gültig; der Arbeitnehmer kann Kündigungsschutzklage erheben.",
 k:"Mitbestimmung",s:"LF1 2.3.1"},
{tg:4,g:"sv-traeger",src:"IZ Übung/72",t:"match",
 q:"Ordnen Sie die Zweige der Sozialversicherung ihrem Träger zu.",
 pairs:[["Krankenversicherung","gesetzliche Krankenkassen (z. B. AOK)"],["Unfallversicherung","Berufsgenossenschaften"],["Rentenversicherung","Deutsche Rentenversicherung"],["Arbeitslosenversicherung","Bundesagentur für Arbeit"],["Pflegeversicherung","Pflegekassen bei den Krankenkassen"]],
 e:"Fünf Zweige; die Krankenkassen ziehen die Beiträge für alle Zweige ein, zu denen Arbeitgeber und Arbeitnehmer beitragen. Die Unfallversicherung zahlt allein der Arbeitgeber, alle anderen werden paritätisch finanziert.",
 k:"Sozialversicherung",s:"LF1 2.4.1"},
{tg:4,g:"sv-prinzip",src:"IZ Übung/73",t:"mc",
 q:"Eine gutverdienende Agentin und ein Auszubildender erhalten bei gleicher Erkrankung dieselben medizinischen Leistungen der Krankenkasse, obwohl sie unterschiedlich hohe Beiträge zahlen. Welches Prinzip steckt dahinter?",
 a:["Solidaritätsprinzip","Äquivalenzprinzip","Versicherungspflichtgrenze","Beitragsbemessungsgrenze","Kapitaldeckungsprinzip"],c:0,
 e:"Solidaritätsprinzip: Leistungen nach Bedarf, nicht nach Beitragshöhe (Kranken-, Pflegeversicherung). Äquivalenzprinzip: Leistung richtet sich nach den gezahlten Beiträgen (Renten-, teils Arbeitslosenversicherung). Die Beitragsbemessungsgrenze deckelt die Beiträge.",
 k:"Sozialversicherung",s:"LF1 2.4.1"},
{tg:4,g:"altersvorsorge",src:"IZ Übung/74",t:"mc",
 q:"Zu welcher Schicht des Drei-Schichten-Modells der Altersvorsorge gehört die Riester-Rente?",
 a:["zur 2. Schicht (Zusatzversorgung)","zur 1. Schicht (Basisversorgung)","zur 3. Schicht (private Versorgung)","zu keiner Schicht, sie ist Teil der gesetzlichen Rente","zur Pflegeversicherung"],c:0,
 e:"1. Schicht: gesetzliche Rente, Versorgungswerke, Basisrente. 2. Schicht: betriebliche Altersvorsorge und Riester-Rente. 3. Schicht: private Vorsorge wie Lebensversicherung, Fonds oder Immobilien.",
 k:"Sozialversicherung",s:"LF1 2.4.3"},
{tg:4,g:"brandfall-verhalten",src:"IZ Übung/75",t:"mc",
 q:"Im Nachbarbüro brennt ein Papierkorb, eine gehbehinderte Kollegin sitzt noch im Raum. Was hat nach dem Absetzen der Brandmeldung Vorrang?",
 a:["die Kollegin in Sicherheit bringen – Menschenrettung geht vor Brandbekämpfung","zuerst den Brand selbst löschen","die Unterlagen vom Schreibtisch retten","den Aufzug rufen, um schneller nach unten zu kommen","die Fenster öffnen, damit der Rauch abzieht"],c:0,
 e:"Abwehrender Brandschutz laut Buch: Brand melden, Hilfsbedürftige in Sicherheit bringen (Menschenrettung vor Brandbekämpfung), Räume verlassen, keine Aufzüge benutzen, Fenster und Türen schließen, Vollzähligkeit prüfen, kleinere Brände selbst löschen, Feuerwehr einweisen.",
 k:"Arbeitsschutz",s:"LF1 3.3"},
{tg:4,g:"pdca",src:"IZ Übung/76",t:"order",
 q:"Umweltmanagementsysteme verbessern sich kontinuierlich nach dem PDCA-Zyklus. Bringen Sie die Phasen in die richtige Reihenfolge.",
 items:["Plan: Ziele und Prozesse festlegen","Do: Maßnahmen durchführen","Check: Ergebnisse überwachen, Abweichungen feststellen","Act: Maßnahmen anpassen und optimieren"],
 e:"Der PDCA-Zyklus ist die Grundlage des kontinuierlichen Verbesserungsprozesses, z. B. im EU-Öko-Audit EMAS. Nach „Act“ beginnt der Zyklus erneut.",
 k:"Umweltschutz",s:"LF1 3.4"},
{tg:4,g:"entgeltfortzahlung",src:"IZ Übung/77",t:"mc",
 q:"Ein Agent ist wegen derselben Erkrankung arbeitsunfähig. Wie lange zahlt der Arbeitgeber das Entgelt nach dem Entgeltfortzahlungsgesetz weiter?",
 a:["bis zu sechs Wochen","bis zu drei Tagen","bis zu drei Monaten","unbegrenzt","gar nicht – ab dem ersten Tag zahlt die Krankenkasse"],c:0,
 e:"Bei Arbeitsunfähigkeit durch Krankheit zahlt der Arbeitgeber bis zu sechs Wochen weiter; danach zahlt die Krankenkasse Krankengeld (ergänzt).",
 k:"Schutzgesetze",s:"LF1 2.2.4"},
{tg:4,g:"arbzg-nacht",src:"IZ Übung/78",t:"mc",
 q:"Welcher Zeitraum ist nach dem Arbeitszeitgesetz Nachtzeit?",
 a:["23 bis 6 Uhr","20 bis 6 Uhr","22 bis 5 Uhr","0 bis 8 Uhr","18 bis 6 Uhr"],c:0,
 e:"§ 2 ArbZG: Nachtzeit ist die Zeit von 23 bis 6 Uhr; Nachtarbeit liegt vor, wenn mehr als zwei Stunden der Nachtzeit umfasst sind. Nicht verwechseln mit dem JArbSchG: Jugendliche dürfen nur zwischen 6 und 20 Uhr beschäftigt werden.",
 k:"Schutzgesetze",s:"LF1 2.2.2"},
{tg:4,g:"jav-wahl",src:"IZ Übung/79",t:"mc",
 q:"Unter welcher Voraussetzung wird in einem Betrieb mit Betriebsrat eine Jugend- und Auszubildendenvertretung (JAV) gewählt?",
 a:["wenn in der Regel mindestens fünf Arbeitnehmer unter 18 Jahren oder Auszubildende unter 25 Jahren beschäftigt sind","wenn mindestens 20 Auszubildende beschäftigt sind","nur wenn die IHK dies anordnet","nur in Betrieben mit mehr als 500 Beschäftigten","wenn die Geschäftsleitung zustimmt"],c:0,
 e:"Das Buch nennt die Grenze von fünf jugendlichen bzw. auszubildenden Beschäftigten; die Altersgrenzen (unter 18 bzw. Auszubildende unter 25) sind ergänzt aus § 60 BetrVG. Die JAV überwacht u. a. die Einhaltung der Schutzvorschriften für Jugendliche und Auszubildende.",
 k:"Mitbestimmung",s:"LF1 2.3.2"}
]};
